### ISSUE TITLE
UseQuestLogSpecialItem Bugsack error

### ISSUE THREAD

**Issue by Rubyurek** [zarillion/handynotes-plugins#101]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'HandyNotes_Shadowlands' hat versucht die geschützte Funktion 'UseQuestLogSpecialItem()' aufzurufen.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTrackerShared.lua"]:95: in function <...ObjectiveTracker\Blizzard_ObjectiveTrackerShared.lua:88

**Comment by zarillion** [comment]
Also reported in #116

**Comment by zarillion** [comment]
I have not personally seen this occur in 9.2 yet. I'm hoping the update to `Krowi_WorldMapButton` fixed the issue. If it is still happening we can reopen the issue or create a new one.
