### ISSUE TITLE
Error Today

### ISSUE THREAD

**Issue by OldWorldRaiders** [zarillion/handynotes-plugins#116]
2x [ADDON_ACTION_FORBIDDEN] AddOn 'HandyNotes' tried to call the protected function 'UseQuestLogSpecialItem()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTrackerShared.lua"]:95: in function <...ObjectiveTracker\Blizzard_ObjectiveTrackerShared.lua:88>

**Comment by zarillion** [comment]
Closing as dup of #101
