### ISSUE TITLE
GetAchievementCriteriaInfo(achievementID, criteriaIndex [,countHidden]), criteria not found

### ISSUE THREAD

**Issue by gixxpunk** [zarillion/handynotes-plugins#12]
1x ...rfaceHandyNotes_Shadowlands\core\rewards-Rewards.lua:38: GetAchievementCriteriaInfo(achievementID, criteriaIndex [,countHidden]), criteria not found
[string "=[C]"]: in function `GetAchievementCriteriaInfo'
[string "@HandyNotes_Shadowlands\core\rewards-Rewards.lua"]:38: in function <...rfaceHandyNotes_Shadowlands\core\rewards.lua:35>
[string "@HandyNotes_Shadowlands\core\rewards-Rewards.lua"]:64: in function `obtained'
[string "@HandyNotes_Shadowlands\core\nodes.lua"]:93: in function `collected'
[string "@HandyNotes_Shadowlands\core\nodes.lua"]:363: in function <HandyNotes_Shadowlands\core\nodes.lua:356>
[string "=(tail call)"]: ?
[string "@HandyNotes_Shadowlands\core\nodes.lua"]:71: in function `display'
[string "@HandyNotes_Shadowlands\core\core.lua"]:162: in function `(for generator)'
[string "@HandyNotes\HandyNotes-v1.5.10-4-g31eee54.lua"]:332: in function <HandyNotes\HandyNotes.lua:320>
[string "=[C]"]: ?
[string "@HandyNotes\HandyNotes-v1.5.10-4-g31eee54.lua"]:56: in function <HandyNotes\HandyNotes.lua:51>
[string "@HandyNotes\HandyNotes-v1.5.10-4-g31eee54.lua"]:316: in function `RefreshAllData'
[string "@Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:559: in function `OnMapChanged'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:234: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:59: in function `SetMapID'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:765: in function `NavigateToCursor'
[string "@Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:110: in function <...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:102>

**Comment by zarillion** [comment]
Thanks for the report. This was fixed in 60dca6c and will be released later today in v5.
