### ISSUE TITLE
Kyrian Assault - Stolen Anima Vessel - Missing Location

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#136]
A third location for KYR_VESSEL1 at 37.44 44.8

**Comment by Krovikan** [comment]
Hello:

This vessel is in the code https://github.com/zarillion/handynotes-plugins/commit/402667c08c427be0afc8b30b3df7e64d59a21dde but the release isn't yet launched.

**Comment by ghost** [comment]
I'll close this then
