### ISSUE TITLE
Korthia cosmetics listed as Unobtainable

### ISSUE THREAD

**Issue by nayab9** [zarillion/handynotes-plugins#137]
Is this a handynotes thing, or a blizzard API thing?

The back cosmetics from rares and chests seem to show unobtainable; are they really unobtainable or is it listed incorrectly?

They are unobtainable on all my characters (all 4 covenants, all armor types...); which would mean these are impossible for me to acquire so that doesn't seem to make sense...

![image](https://user-images.githubusercontent.com/1916171/128435970-26f9e042-2269-404c-92b4-c6502916928a.png)

**Comment by zarillion** [comment]
This should be fixed now for the upcoming release.
