### ISSUE TITLE
Spectral chest location

### ISSUE THREAD

**Issue by N6REJ** [zarillion/handynotes-plugins#138]
Would you please add the key locations to HN
/way 61.01 58.69 1
/way 62.18 57.71 2
/way 60.11 56.52 3
/way 59.21 56.79 4
/way 52.10 53.21 5
/way 50.48 53.67 6
/way 52.61 49.71 7
/way 54.18 50.60 8
/way 57.50 49.32 9
/way 59.09 48.68 10
/way 61.19 47.61 11
/way 62.82 51.32 12
/way 62.10 55.40 Spectral Bound Chest

**Comment by Dathwada** [comment]
The chest is already added with all keys.

**Comment by zarillion** [comment]
Make sure you have "Treasures" enabled. Left-click the spectral chest icon to pin the key locations to your map and minimap as you collect them.

**Comment by N6REJ** [comment]
I used /hnnew to mark each one but not sure how to save it..   But no clue how to share it, but its sounding like you already did it?
![image](https://user-images.githubusercontent.com/1850089/128439126-6a1da85f-cec6-43c8-a04d-d8b1f0ef3475.png)
 is what I have for korthia..
 and 
 
![image](https://user-images.githubusercontent.com/1850089/128439162-9f12659f-d344-4ac5-bc44-256712b4670f.png)
 are the locations I marked... I used "reagent" cause I couldn't find a better choice.
