### ISSUE TITLE
transmog rewards

### ISSUE THREAD

**Issue by drsleo** [zarillion/handynotes-plugins#143]
Improved the tracking of transmog rewards. Appearances known from other items are now recognized.

can implement an option to revert this, please, your addons are perfect and awesome, thanks for everything

**Comment by Krovikan** [comment]
You talk about this? (from the v38 Notes):

Transmogs for other classes are now hidden by default. The "Show unobtainable transmog" option has been added to restore the previous functionality.

**Comment by drsleo** [comment]
no no, from changing transmogs, Mark an item as collected based on shared appearances.

**Comment by zarillion** [comment]
Hi @drsleo. I believe I know what option you are talking about. ATT calls it "Completionist" mode:

![image](https://user-images.githubusercontent.com/64381982/129233712-a848c404-775c-48a7-b72f-b2bc0b391eb3.png)

For our plugin, I prefer the current behavior. I believe the majority of people using our plugin want to get what they can from the zone and then move on. For the truly hard-core, I would recommend using ATT to track which appearances you do not know from specific items in the zone as a supplement to this plugin.
