### ISSUE TITLE
Shadowlands\core\map.lua:284: attempt to perform arithmetic on field 'facing' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [zarillion/handynotes-plugins#144]
Got this while doing the Uther memory chain

3x HandyNotes_Shadowlands\core\map.lua:284: attempt to perform arithmetic on field 'facing' (a nil value)
[string "@HandyNotes_Shadowlands\core\map.lua"]:284: in function `UpdateRotation'
[string "@HandyNotes_Shadowlands\core\map.lua"]:247: in function `RefreshAllRotations'
[string "@HandyNotes_Shadowlands\core\map.lua"]:255: in function `OnUpdate'
[string "@HandyNotes_Shadowlands\core\map.lua"]:289: in function <HandyNotes_Shadowlands\core\map.lua:287>

Locals:
self = HandyNotes_ShadowlandsPin1 {
 0 = <userdata>
 acquired = true
 OnLoad = <function> defined @HandyNotes_Shadowlands\core\map.lua:260
 minimap = true
 rotation = 0.352044
 OnAcquired = <function> defined @HandyNotes_Shadowlands\core\map.lua:266
 frameOffset = 0
 provider = HandyNotes_ShadowlandsMinimapDP {
 }
 UpdateRotation = <function> defined @HandyNotes_Shadowlands\core\map.lua:280
 OnReleased = <function> defined @HandyNotes_Shadowlands\core\map.lua:273
 texture = <unnamed> {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 6.635230
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'facing' (a nil value)"

**Comment by zarillion** [comment]
Thanks for the report. I've put some more safeguards in that should help in the next release.
