### ISSUE TITLE
Make option for turn off the new "improved" transmog tracking 

### ISSUE THREAD

**Issue by vsaR1SK** [zarillion/handynotes-plugins#145]
v38 Changelog:
`Improved the tracking of transmog rewards. Appearances known from other items are now recognized.`

Some people (like me) prefer completionist mode, so we want to track items may have learned from other sources.

Please, make option for turn this on/off.

**Comment by zarillion** [comment]
As mentioned in #143, I do not currently plan to support this mode as I think ATT does a fairly good job of it already.

**Comment by vsaR1SK** [comment]
Absurd!
Please, just add a little checkbox
