### ISSUE TITLE
Incorrect ruRU translation

### ISSUE THREAD

**Issue by tomrus88** [zarillion/handynotes-plugins#148]
Fix below
```Diff
 plugins/09_Shadowlands/localization/ruRU.lua | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/plugins/09_Shadowlands/localization/ruRU.lua b/plugins/09_Shadowlands/localization/ruRU.lua
index 2d24219..f41cbc6 100644
--- a/plugins/09_Shadowlands/localization/ruRU.lua
+++ b/plugins/09_Shadowlands/localization/ruRU.lua
@@ -169,7 +169,7 @@ L["vesper_of_purity"] = "Колокол Чистоты"
 L["vesper_of_wisdom"] = "Колокол Мудрости"
 L["vespers_ascended_note"] = "Активируйте этот колокол одновременно с четырьмя другими колоколами, чтобы призвать {npc:170899} в Горнило претендентов."
 L["options_icons_vespers"] = "{achievement:14734}"
-L["options_icons_vespers_desc"] = "Показать расположение колоколов для достижения {достижение:14734}."
+L["options_icons_vespers_desc"] = "Показать расположение колоколов для достижения {achievement:14734}."
 
 L["anima_shard"] = "Пропавшие осколки анимы"
 L["anima_shard_61225"] = "На нижней площадке под мостомe."
```

**Comment by Krovikan** [comment]
It's not possible translate the tags, I guess.

All locale files have the tags in english, maybe restricted for LUA syntax or by wowhead urls.

If you want make a PR and the Author will be decide.

**Comment by Krovikan** [comment]
> It's not possible translate the tags, I guess.
> 
> All locale files have the tags in english, maybe restricted for LUA syntax or by wowhead urls.
> 
> If you want make a PR and the Author will be decide.

Sorry, you are right with the change. I interpreted you backwards.

Changes are made in the commit https://github.com/zarillion/handynotes-plugins/commit/02a0004b33361b80e13004d7f244d67adf83ca8f by Collaborator of ruRU and you will can see in the next release.
