### ISSUE TITLE
ADDON_ACTION_BLOCKED

### ISSUE THREAD

**Issue by lovs2build** [zarillion/handynotes-plugins#154]
Trying to upgrade Koritha gear, had to disable add on

1x [ADDON_ACTION_BLOCKED] AddOn 'HandyNotes_Shadowlands' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@FrameXML\LFGList.lua"]:3508: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@FrameXML\LFGList.lua"]:2576: in function <FrameXML\LFGList.lua:2573>

**Comment by N6REJ** [comment]
looks to me like it is ["LFGlist"](https://www.curseforge.com/wow/addons/lfglist) addon not handynotes

**Comment by lovs2build** [comment]
I don't have that add on installed, and from reading that add on has been broke since 2019. What about world quest list, I do know sometimes that add on affects upgrading Korthia gear, however when this error popped up it WQL was disabled.

OK after investagting this LFGlist.lua it is a Blizzard UI interface (the korthia gear upgrading?) I did serach of my add ons and it found no LFGlist.lua

**Comment by N6REJ** [comment]
what I would suggest is you turn off ALL addons except handynotes and try the issue.  If it still happens then you know for sure.
if it doesn't happen then turn things on one by one until you narrow it down.
I can't see any logical reason why handynotes would cause this issue.

**Comment by 1701NCC** [comment]
```
20x [ADDON_ACTION_BLOCKED] AddOn 'HandyNotes_BattleForAzeroth' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@FrameXML\LFGList.lua"]:3508: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@FrameXML\LFGList.lua"]:2576: in function <FrameXML\LFGList.lua:2573>
```

Having the same issue, Did you ever solve this issue or find the cause lovs2build ?

**Comment by lovs2build** [comment]
> ```
> 20x [ADDON_ACTION_BLOCKED] AddOn 'HandyNotes_BattleForAzeroth' tried to call the protected function 'GetPlaystyleString()'.
> [string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
> [string "=[C]"]: in function `GetPlaystyleString'
> [string "@FrameXML\LFGList.lua"]:3508: in function `LFGListUtil_SetSearchEntryTooltip'
> [string "@FrameXML\LFGList.lua"]:2576: in function <FrameXML\LFGList.lua:2573>
> ```
> 
> Having the same issue, Did you ever solve this issue or find the cause lovs2build ?

Do you have world quest list? This is what was causing it for it, when I disabled it, I had no problems, if not then follow advice by creator of addon below my OP to figure out which addon is causing error. Good luck
