### ISSUE TITLE
Error , when i open Map in Korthia

### ISSUE THREAD

**Issue by devil81** [zarillion/handynotes-plugins#155]
Message: Interface\SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y2' (a nil value)
Time: Tue Nov 23 17:29:06 2021
Count: 1
Stack: Interface\SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y2' (a nil value)
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:109: in function `Connect'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:56: in function `ConnectPins'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:41: in function `RefreshAllData'
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:580: in function <...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:579>
[string "=[C]"]: in function `secureexecuterange'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:583: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:234: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:233>
[string "=[C]"]: ?
[string "=[C]"]: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:60: in function `SetMapID'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:245: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:243>
...
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2958: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2764: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2671: in function <Interface\FrameXML\UIParent.lua:2667>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3522: in function `ShowUIPanel'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:440: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals: self = <unnamed> {
 0 = <userdata>
 Line = <unnamed> {
 }
 point = <table> {
 }
 Connect = <function> defined @Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua:97
}
pin1 = <unnamed> {
 SetNudgeSourceMagnitude = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:224
 GetGlobalPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:311
 PanTo = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:318
 connectionOut = <unnamed> {
 }
 owningMap = WorldMapFrame {
 }
 ClearNudgeSettings = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:199
 OnMapInsetMouseLeave = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:195
 normalizedY = 0.638500
 SetNudgeFactor = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:286
 GetPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:306
 UseFrameLevelType = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:423
 GetNudgeSourceZoomedInMagnitude = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:233
 SetScaleStyle = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:359
 OnClick = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:152
 GetNudgeSourcePinZoomedInNudgeFactor = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:269
 GetNudgeSourceRadius = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:220
 pinFrameLe

**Comment by Krovikan** [comment]
Sorry, but you are wrong with the addon.

Your report is about 'HandyNotes_ShadowlandsTreasures' and our plugin is called 'HandyNotes_Shadowlands'.

Please, report to correct addon.
