### ISSUE TITLE
Bugsack error on login since 9.2.0 update

### ISSUE THREAD

**Issue by addonaddict** [zarillion/handynotes-plugins#158]
4x HandyNotes_Shadowlands\core\map.lua:81: Missing world coords: (2027: 65645023) => ???
[string "=[C]"]: in function `error'
[string "@HandyNotes_Shadowlands\core\map.lua"]:81: in function `AddNode'
[string "@HandyNotes_Shadowlands\core\map.lua"]:38: in function <HandyNotes_Shadowlands\core\map.lua:37>
[string "@HandyNotes_Shadowlands\zones\zereth_mortis.lua"]:648: in main chunk

Locals:
(*temporary) = "Missing world coords: (2027: 65645023) => ???"

**Comment by zarillion** [comment]
@addonaddict Is this happening regularly for you? I have not had any other reports of this error, nor have I been able to reproduce it myself.

**Comment by addonaddict** [comment]
I believe it went away after recent update but I will check again
I have many other handy notes plugins, so it couldve been caused by that
Thanks

**Comment by zarillion** [comment]
I will close this for now then. Feel free to reopen if it resurfaces.
