### ISSUE TITLE
Czech localization

### ISSUE THREAD

**Issue by nEON7** [zarillion/handynotes-plugins#159]
Hi there, I can make Czech translation.

**Comment by Krovikan** [comment]
You are free to enter to our Discord: https://discord.gg/Q9NeB9Sf

**Comment by Dathwada** [comment]
Czech isn't a supported language by the wow client.

### Supported langages are:
* English
* German
* Spanish
* Mexican Spanish
* French
* Italian
* Korean
* Brazilian Portuguese
* Russian
* Simplified Chinese
* Traditional Chinese
