### ISSUE TITLE
Repair and Restore 59740 add

### ISSUE THREAD

**Issue by zkekahs2** [zarillion/handynotes-plugins#160]
wowhead comments
Today's Broken Mirror Macro

Skript to display the current mirror group:
/run m={61879,61883,61885,61886} for g,n in pairs(m) do C_QuestLog.RemoveWorldQuestWatch(n) a=C_QuestLog.AddWorldQuestWatch(n) c=C_QuestLog.IsQuestFlaggedCompleted(n) if a or c then print("\124cff00FE00Mirror Group " .. g .. " active\124r") end end

and

Not sure how many people are still farming these mirrors but I found something that may stop your need to guess which Mirror group is up on a given day or run to Wowhead and hope it's listed on the front page:
It seems that the mirror group of the day corresponds to the daily Revendreth Pet Battle World Quest:

Scorch = Mirror group 1
Sylla = Mirror group 2
Eyegor = Mirror group 3
Addius = Mirror group 4

Can it be displayed in Handy Note?

**Comment by zarillion** [comment]
I have not been playing my venthyr recently. When I get time I need to examine this for a week or so before I put it into the plugin. If it works as expected that would be awesome!

**Comment by Krovikan** [comment]
@zkekahs2 After 7 months I'll close this issue for now. Be free to reopen if is the case.

Regards
