### ISSUE TITLE
LUA  error when mouseover Anima Shard on in Bastion

### ISSUE THREAD

**Issue by eloxole** [zarillion/handynotes-plugins#161]
Keep getting LUA error when mouseover Anima Shard on world map in Bastion.

Message: ...\HandyNotes_ShadowlandsTreasures\handler\handler.lua:468: attempt to compare nil with number
Time: Tue Mar  8 19:25:16 2022
Count: 7
Stack: ...\HandyNotes_ShadowlandsTreasures\handler\handler.lua:468: attempt to compare nil with number
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\handler.lua"]:468: in function <...\HandyNotes_ShadowlandsTreasures\handler\handler.lua:467>
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\handler.lua"]:527: in function <...\HandyNotes_ShadowlandsTreasures\handler\handler.lua:483>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\handler.lua"]:686: in function <...\HandyNotes_ShadowlandsTreasures\handler\handler.lua:662>
[string "=[C]"]: ?
[string "@Interface\AddOns\HandyNotes\HandyNotes.lua"]:56: in function <Interface\AddOns\HandyNotes\HandyNotes.lua:51>
[string "@Interface\AddOns\HandyNotes\HandyNotes.lua"]:166: in function `OnEnter'
[string "@Interface\AddOns\HandyNotes\HandyNotes.lua"]:391: in function <Interface\AddOns\HandyNotes\HandyNotes.lua:390>

Locals: <none>

**Comment by Krovikan** [comment]
This is not our fault.

> Message: ...\**HandyNotes_ShadowlandsTreasures**\handler\handler.lua:468: attempt to compare nil with number Time: Tue Mar 8 19:25:16 2022 Count: 7

Our addon is called HandyNotes Shadowlands, in the name we don't have the word Treasures. Your report is for a similar addon with a very similar name.

https://www.curseforge.com/wow/addons/handynotes-shadowlands-treasures

That addon is a copy & paste of our addon. Even the name of release is the same.

**Comment by eloxole** [comment]
My bad, I overlooked the name distinction.
