### ISSUE TITLE
Echoed Jiro icons should use the same color as their buffs

### ISSUE THREAD

**Issue by cremor** [zarillion/handynotes-plugins#162]
The icons for Echoed Jiro use the same three colors as the buffs that you get from them - red, green and blue. But the color of the icons does not match the color of the buff. That can easily be seen in the tooltip that is shown for an Echoed Jiro icon.
Could you please change the color of the icons so that they match the buff color?

**Comment by zarillion** [comment]
Thanks for the report, this has been fixed.
