### ISSUE TITLE
FPS drop/stutterin in SL when Jumping / Flying

### ISSUE THREAD

**Issue by Emoosch** [zarillion/handynotes-plugins#164]
Hello,

i have the "old" issue again. > https://github.com/zarillion/handynotes-plugins/issues/75

When im jumping and when im flying, it drops the fps and feels like freeze/stutter. (really annoying while flying :D)

Deactivate HandyNotes Shadowlands fixes the problem.

Maybe a new issue after the update for flying in Zereth Mortis?

Edit:
Also in the area "Catalys Gardens", while doing the WQ where i have to kill 12 npcs, the games feels like 40-50fps, while i reach the capped 140fps. But still with the drops/stutter issue.

**Comment by zarillion** [comment]
No one else has commented on this and although I've kept an eye out I have not seen this personally since the last round of performance tuning. I'll close this for now.
