### ISSUE TITLE
Clearify Ripened Protopear note

### ISSUE THREAD

**Issue by cremor** [zarillion/handynotes-plugins#168]
The note for Ripened Protopear should be updated to make it clear that each cloud has to be brought to the treasure separately since the buff doesn't stack.
This is especially true for the german note since it explicitly mentions "Stapel" (stacks), which is wrong.

**Comment by Krovikan** [comment]
The next release will have this clarify do it in https://github.com/zarillion/handynotes-plugins/commit/c2ad07d1d75c4e81a9e638dd1f083b14f695bfe2

The translators will do their part.

Feel free to open the issue for any problem.
