### ISSUE TITLE
Completed treasures no longer hiding

### ISSUE THREAD

**Issue by Slackluster** [zarillion/handynotes-plugins#180]
Hello. I have the 'Show completed' setting and the 'Use character achievements' setting disabled, but completed treasures are still showing up for me.

![image](https://user-images.githubusercontent.com/29845810/175291756-4b8fcaeb-b6a8-40a5-a195-4753be8f0667.png)

**Comment by zarillion** [comment]
This is by design at the moment as most treasures are tied to per-character quests and not achievement criteria. We may redesign this in a future update, but nothing on the road map at this time.
