### ISSUE TITLE
Shadowlands: Additional Stygia Nexus coordinates

### ISSUE THREAD

**Issue by Taizunz** [zarillion/handynotes-plugins#187]
Here's a bunch of Stygia Nexus coordinates for ones that are missing in the plugin that I came across today:
```
46.19, 81.36
On the ground outside Death's Roar

45.12, 66.71
Next to a grapple point

61.09, 69.17
Inside a small cave with a bunch of mawrats

52.90, 70.27
On a rock, next to a grapple point

23.19, 69.96
On the wall on top of ramparts, can access via nearby grapple points

33.18, 20.58
On top of rock, next to grapple point

30.09, 28.27
Floating next to a rock ledge, next to a grapple point

18.92, 46.33
Behind Eternas the Tormentor

26.74, 44.96
On the ground under the glowing rock formations, next to a Coalesced Agony

30.05, 65.78
On slanted rock next to wall
```

Unfortunately I hadn't read the tip about using the macro for getting proper coordinates and mapID until now, so I'm sorry about not being able to provide that. Is there an easy way to convert the above coordinates into ones that are usable in the plugin? If not, I can probably go back and retrieve those at some point as well.

**Comment by zarillion** [comment]
Thanks for the data @Taizunz! Sorry for the late response, I just added these points to our map. They will go out with the next release of the Shadowlands plugin.
