### ISSUE TITLE
only count pets as completed when max amount is reached

### ISSUE THREAD

**Issue by katzner** [zarillion/handynotes-plugins#190]
I always collect the maximum number of pets (usually 3)  from rare mobs. Sometimes there are different breeds or I need more than one of them for specific fights... 
I would love an **option** for HandyNotes to **only count the reward as completed when I got the maximum number of the specific pet**.

**Comment by zarillion** [comment]
I'm going to close this as a bit of a niche request. While there are some cases where having multiples of a pet can make a certain trainer encounter easier, in all of those cases the trainers can also be defeated using a team of unique pets.

In these cases I usually recommend an addon aimed at more hardcore collectors, like All The Things (I'm not sure if it has this option of not).
