### ISSUE TITLE
SL interface set incorrectly in release

### ISSUE THREAD

**Issue by kimnnmadsen** [zarillion/handynotes-plugins#21]
`## Interface: 90002`
is set in v40 of VisionOfNZoth
but should be
`## Interface: 90001`
as in source

**Comment by kimnnmadsen** [comment]
The same is the case for MechagonAndNazjatar-v15

**Comment by Krovikan** [comment]
Maybe this night the addon will have a new release fixing the problem. Thanks for the warning!

**Comment by zarillion** [comment]
New versions of each addon have been released.
