### ISSUE TITLE
Addon seems to be missing rares and some rares are not aligned on the map

### ISSUE THREAD

**Issue by Critzie** [zarillion/handynotes-plugins#214]
Addon seems to be missing rares and some rares are not aligned on the map

[Picture of not aligned rare](https://imgur.com/a/wDFwGZM)

**Comment by zarillion** [comment]
Thanks for the report.

We'll be filling in the remaining rares as we all play retail launch. The existing data is based on what was found/figured out on beta, and some rares are still unknown or unfound.

**Comment by Critzie** [comment]
Awesome, just thought i'd point out the none aligned icons and missing rares :) if i find any i'll report it
