### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DDirtyDan** [zarillion/handynotes-plugins#218]
Message: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:285: attempt to concatenate a nil value
Time: Tue Nov 29 15:48:44 2022
Count: 5
Stack: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:285: attempt to concatenate a nil value
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/nodes.lua"]:285: in function `Render'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/core.lua"]:116: in function <...terface/AddOns/HandyNotes_Dragonflight/core/core.lua:115>

Locals: self = <table> {
 _prepared = true
 note = "The required item can be found at Renown 21 with the Dragonscale Expedition in in Expedition Scout's Packs and Disturbed Dirts."
 requires = <table> {
 }
 glow = <table> {
 }
 __address = "0000023FF0690900"
 rewards = <table> {
 }
 quest = <table> {
 }
 __class = <table> {
 }
}
tooltip = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined =[C]:-1
 SetUnit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 waitingForData = false
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 OnLoad = <function> defined @Interface/FrameXML/GameTooltip.lua:927
 shouldRefreshData = false
 SetInfoBackdropStyle = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:338
 SetTotem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 shoppingTooltips = <table> {
 }
 SetSocketGem = <function> defined =[C]:-1
 updateTooltipTimer = 0.149000
 ItemTooltip = Frame {
 }
 StatusBar = GameTooltipStatusBar {
 }
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetUnit = <function> defined @Interface/FrameXML/GameTooltip.lua:994
 SetOwnedItemByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextRight1 = GameTooltipTextRight1 {
 }
 SetEnhancedConduit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined @Interface/AddOns/Altoholic/Services/Tooltip.lua:616
 SetQuestCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsDataRefresh = true
 SetWeeklyReward = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetPvpBrawl = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAchievementByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsItemComparison = true
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236
 ProcessLines = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:293
 NineSlice

**Comment by Dathwada** [comment]
closed because of duplicated issue, see [#213].
