### ISSUE TITLE
When hovering a lot of map icons I get this error

### ISSUE THREAD

**Issue by antedap** [zarillion/handynotes-plugins#220]
25x HandyNotes_Dragonflight/core/nodes.lua:285: attempt to concatenate a nil value
[string "@HandyNotes_Dragonflight/core/nodes.lua"]:285: in function `Render'
[string "@HandyNotes_Dragonflight/core/core.lua"]:116: in function <HandyNotes_Dragonflight/core/core.lua:115>

Locals:
self = <table> {
 _prepared = true
 note = "The required item can be found at Renown 21 with the Dragonscale Expedition in in Expedition Scout's Packs and Disturbed Dirts."
 requires = <table> {
 }
 glow = <table> {
 }
 __address = "000002122B65DC40"
 rewards = <table> {
 }
 quest = <table> {
 }
 __class = <table> {
 }
}
tooltip = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 __style = 1
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined =[C]:-1
 SetSocketGem = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined =[C]:-1
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:990
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined @Altoholic/Services/Tooltip.lua:616
 SetMerchantItem = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:236
 NineSlice = Frame {
 }
 OnLoad = <function> defined @FrameXML/GameTooltip.lua:927
 SetUnitDebuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItem = <function> defined =[C]:-1
 SetCurrencyByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSpellBookItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 textLeft1Font = "GameTooltipHeaderText"
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 hasMoney = 1
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 textRight2Font = "GameTooltipText"
 windInspectLoaded = false
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuff = <function> defined =[C]:-1
 factionFrame = Texture {
 }
 SetMountBySpellID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetToyByItemID = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:344
 IsTooltipType = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:351
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 StatusBar = GameTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetConduit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetItem = <function> defined @FrameXML/GameTooltip.lua:986
 SetRecipeResultItem = <function> defined =[C]:-1
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetTotem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 SetInfoBackdropStyle = <func

**Comment by antedap** [comment]
![Screenshot_42](https://user-images.githubusercontent.com/73392980/204817219-48cf7371-673a-466c-a429-940c749161a3.png)

**Comment by Dathwada** [comment]
closed because of duplicated issue, see [#213].
