### ISSUE TITLE
Missing Dragon Riding Glyph Thaldraszus at Gelikyr Overlook.

### ISSUE THREAD

**Issue by BigFire321** [zarillion/handynotes-plugins#224]
Map is missing Dragon riding glyph @ Thaldraszus at Gelikyr Overlook.

**Comment by Dathwada** [comment]
I think its just hidden under the rare 'Craggravated Elemental'

**Comment by zarillion** [comment]
I went through all the glyphs yesterday using the data @Dathwada put in and I ended up with a complete set. Its probably hidden under an existing node like @Dathwada said. I'll close this for now.
