### ISSUE TITLE
rare names in german missing

### ISSUE THREAD

**Issue by Numira123** [zarillion/handynotes-plugins#228]
german rare names are missing in handynotes dragonflight
https://ibb.co/z8rHj7n

**Comment by Dathwada** [comment]
Have you tried to hover a second time over this node?

**Comment by Numira123** [comment]
yes 3 times

**Comment by Dathwada** [comment]
that's odd (I also play in German and don't have this problem), only this rare ?

**Comment by Numira123** [comment]
other rares too

**Comment by zarillion** [comment]
Is this still going on? I haven't seen any other reports. Feel free to reopen if it is still happening.

**Comment by Numira123** [comment]
yes still happening

**Comment by Dathwada** [comment]
We solved this issue in a Discord PM and figured out that his Tukui map was causing this.
