### ISSUE TITLE
Don't hide Dragonscale Expedition Flag POIs after achievement

### ISSUE THREAD

**Issue by Taizunz** [zarillion/handynotes-plugins#229]
These, for reference:
![image](https://user-images.githubusercontent.com/15648000/205428244-b58aef0b-7c70-475d-9c54-37043b44df34.png)

When you get the achievement, the remaining ones are all hidden. But they give a substantial amount of rep towards renown, so hiding all the unfinished ones is counterproductive, and the only way to display them again via in-game options is by showing all completed POIs. This isn't very ideal though, as there's no easy way to tell which ones you've already done and which ones are the remaining ones, so you'll be doing a lot of guess-work.

A more accurate way is to remove the "rewards" part pertaining to these flags in `common.lua`, this way only the completed ones are hidden, and when earning the achievement all the remaining ones don't get hidden either. This of course comes with the side effect that you'll no longer be able to see your achievement progress when hovering your mouse over one of the flag icons - I'm not smart enough to figure out how to keep just enough of the rewards code in there to keep the tracking in place but prevent it from hiding everything upon achievement completion.

**Comment by Dathwada** [comment]
You are using version 5 or older, was already updated in version 6 and we are now at version 7, please consider to update your addon.

**Comment by Taizunz** [comment]
I'm on version 7. I check for addon updates several times every day.
![image](https://user-images.githubusercontent.com/15648000/205439618-9bc321e1-8eb2-4759-8926-8c648da95421.png)

And looking at the changelog for both v5, v6 and v7, there's nothing to indicate that what I'm talking about has been altered.

EDIT: I suspect you misunderstand my proposal. I'm not asking for missing flags to be added - as that seems to be the only thing that was touched on in v6, I'm asking for the unclaimed flags not to be hidden when the achievement has been earned because there's still a lot of rep to be earned.

**Comment by Dathwada** [comment]
your screenshot is from version 5 or older because in version 6 and newer the reputation was set to 250 and not 300.
here is the commit with the updates: [[#43294]](https://github.com/zarillion/handynotes-plugins/commit/43294a165f84c7f79f01365e2dc7ed5f7fa2a255)

EDIT: I have not misunderstood you, this should be fixed with the commit above as well.

**Comment by Taizunz** [comment]
Oh, you are right.
I suspect I may have forgotten to /reload between updating my addons, as my client has been running for a long while. My bad.
