### ISSUE TITLE
Dragonflight: tailoring profession knowledge treasures

### ISSUE THREAD

**Issue by benhev** [zarillion/handynotes-plugins#231]
Profession knowledge treasures for tailoring do not disappear from the map after being picked up.
I have "show completed" off and I can confirm that it seems to work for enchanting treasures.

**Comment by adavak** [comment]
some item quest id was nil, if not have record about it the icon will not disappear.

for normal player, just waiting up comming release about that.

or you can help to using debug mode to tell us the quest id what is it.

**Comment by antedap** [comment]
I have found some, I'll update the list in time:

Wind-Blessed Hide 198696
Spare Djaradin Tools 198667
Decayed Scales 198690
Decay-Infused Tanning Oil 198658

**Comment by Dathwada** [comment]
These are only item ids and not the hidden quest ids.

**Comment by antedap** [comment]
oh :\ how can I find them?

**Comment by Dathwada** [comment]
[How to enable development options](https://github.com/zarillion/handynotes-plugins#development-options)

and enable under Options --> AddOns --> HandyNotes --> Plugins -->10 - Dragonflight --> General --> Debug Quest IDs

If you loot the profession knowledge treasures the hidden quest ids will be printed in the chat.

e.g. Quest 70781 changed: false => true

**Comment by antedap** [comment]
Thank you! I presume I can't see already looted quest id?

**Comment by Dathwada** [comment]
No, you would have to do them with another character.

**Comment by antedap** [comment]
Dammit, thanks again

**Comment by benhev** [comment]
Unfortunately I don't have another tailor to look for the QuestID of the ones I have already picked up but I can add some that I come across going forward.

Elysa Raywinder (in Valdrakken) gives 5 knowledge and is associated with QuestID 70260.

Please let me know if you need any more information.

**Comment by adavak** [comment]
all tailoring profession questid done. upgrade to lastest version.
