### ISSUE TITLE
bad argument #1 to 'ipairs'

### ISSUE THREAD

**Issue by the-quality** [zarillion/handynotes-plugins#241]
Hi,

no idea, where it come from, but since today i got this message

`Message: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:226: bad argument #1 to 'ipairs' (table expected, got function)
Time: Fri Dec  9 11:11:33 2022
Count: 1
Stack: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:226: bad argument #1 to 'ipairs' (table expected, got function)
[string "=[C]"]: in function `ipairs'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/nodes.lua"]:226: in function `Prepare'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/map.lua"]:161: in function `Prepare'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/core.lua"]:213: in function <...terface/AddOns/HandyNotes_Dragonflight/core/core.lua:202>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:443: in function `UpdateMinimapPlugin'
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:502: in function `?'
[string "@Interface/AddOns/ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0.lua"]:119: in function <...ventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0.lua"]:29: in function <...ventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/core.lua"]:261: in function `RefreshImmediate'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/core.lua"]:256: in function <...terface/AddOns/HandyNotes_Dragonflight/core/core.lua:254>

Locals: <none>`

i am using version v15

maybe you can help here

thank you

**Comment by N6REJ** [comment]
same here and I JUST updated 2 minutes ago...
```
3x HandyNotes_Dragonflight/core/nodes.lua:226: bad argument #1 to 'ipairs' (table expected, got function)
[string "=[C]"]: in function `ipairs'
[string "@HandyNotes_Dragonflight/core/nodes.lua"]:226: in function `Prepare'
[string "@HandyNotes_Dragonflight/core/map.lua"]:161: in function `Prepare'
[string "@HandyNotes_Dragonflight/core/core.lua"]:213: in function <HandyNotes_Dragonflight/core/core.lua:202>
[string "=(tail call)"]: ?
[string "@HandyNotes/HandyNotes.lua"]:443: in function <HandyNotes/HandyNotes.lua:429>
[string "=[C]"]: ?
[string "@HandyNotes/HandyNotes.lua"]:56: in function <HandyNotes/HandyNotes.lua:51>
[string "@HandyNotes/HandyNotes.lua"]:493: in function `?'
[string "@AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@GatherMate2/Libs/HereBeDragons/HereBeDragons-2.0-22.lua"]:300: in function <...GatherMate2/Libs/HereBeDragons/HereBeDragons-2.0.lua:283>
[string "@GatherMate2/Libs/HereBeDragons/HereBeDragons-2.0-22.lua"]:330: in function <...GatherMate2/Libs/HereBeDragons/HereBeDragons-2.0.lua:329>
```

**Comment by Krovikan** [comment]
Thanks for the reports. Will be fixed soon in the next release.

Regards
