### ISSUE TITLE
Lua error in v15

### ISSUE THREAD

**Issue by sehra** [zarillion/handynotes-plugins#242]
```
Message: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:226: bad argument #1 to 'ipairs' (table expected, got function)
Time: Fri Dec  9 11:05:58 2022
Count: 1
Stack: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:226: bad argument #1 to 'ipairs' (table expected, got function)
[string "=(tail call)"]: ?
[string "=[C]"]: in function `ipairs'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/nodes.lua"]:226: in function `Prepare'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/map.lua"]:161: in function `Prepare'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/core.lua"]:213: in function <...terface/AddOns/HandyNotes_Dragonflight/core/core.lua:202>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:443: in function <Interface/AddOns/HandyNotes/HandyNotes.lua:429>
[string "=[C]"]: ?
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:56: in function <Interface/AddOns/HandyNotes/HandyNotes.lua:51>
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:493: in function `?'
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua"]:310: in function <.../HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua:293>
[string "@Interface/AddOns/HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua"]:340: in function <.../HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua:339>

Locals: <none>
```

Likely related to https://github.com/zarillion/handynotes-plugins/commit/cfd07ce6907bd89fa1ef33c9ef1795e01ee2c2f9#diff-e635d0739fb2e182fb1258a6c5ad68a17bc5f7deba4fd83cecccca2020457866R400-R402

**Comment by zucee** [comment]
Message: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:226: bad argument #1 to 'ipairs' (table expected, got function)
Time: Fri Dec  9 12:02:28 2022
Count: 26
Stack: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:226: bad argument #1 to 'ipairs' (table expected, got function)

Locals: <none>


And this constantly after in Valdrakken.

**Comment by Akhaim** [comment]
Can confirm. same issue in Valdraken for me

**Comment by GhostReapersWorld** [comment]
Can also confirm. The same error only occurs in Valdrakken.

Edit: I get this error also while questing in Thaldraszus.

**Comment by koolman007** [comment]
HandyNotes_Dragonflight/core/nodes.lua:226: bad argument #1 to 'ipairs' (table expected, got function)
[string "=[C]"]: in function `ipairs'
[string "@HandyNotes_Dragonflight/core/nodes.lua"]:226: in function `Prepare'
[string "@HandyNotes_Dragonflight/core/map.lua"]:161: in function `Prepare'
[string "@HandyNotes_Dragonflight/core/core.lua"]:213: in function <HandyNotes_Dragonflight/core/core.lua:202>
[string "=(tail call)"]: ?
[string "@HandyNotes/HandyNotes.lua"]:443: in function <HandyNotes/HandyNotes.lua:429>
[string "=[C]"]: ?
[string "@HandyNotes/HandyNotes.lua"]:56: in function <HandyNotes/HandyNotes.lua:51>
[string "@HandyNotes/HandyNotes.lua"]:493: in function `?'
[string "@TomTom/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@TomTom/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@GatherMate2/Libs/HereBeDragons/HereBeDragons-2.0-22.lua"]:300: in function <...GatherMate2/Libs/HereBeDragons/HereBeDragons-2.0.lua:283>
[string "@GatherMate2/Libs/HereBeDragons/HereBeDragons-2.0-22.lua"]:330: in function <...GatherMate2/Libs/HereBeDragons/HereBeDragons-2.0.lua:329>

**Comment by NGTagger** [comment]
Same thing. Throws these LUA error as soon as I open the map in the Dragon Isles.

**Comment by G1ZMO** [comment]
19x HandyNotes_Dragonflight/core/nodes.lua:226: bad argument #1 to 'ipairs' (table expected, got function)
[string "=[C]"]: in function `ipairs'
[string "@HandyNotes_Dragonflight/core/nodes.lua"]:226: in function `Prepare'
[string "@HandyNotes_Dragonflight/core/map.lua"]:161: in function `Prepare'
[string "@HandyNotes_Dragonflight/core/core.lua"]:213: in function <HandyNotes_Dragonflight/core/core.lua:202>
[string "=(tail call)"]: ?
[string "@HandyNotes/HandyNotes.lua"]:443: in function <HandyNotes/HandyNotes.lua:429>
[string "=[C]"]: ?
[string "@HandyNotes/HandyNotes.lua"]:56: in function <HandyNotes/HandyNotes.lua:51>
[string "@HandyNotes/HandyNotes.lua"]:493: in function `?'
[string "@Accountant/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Accountant/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Accountant/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0-22.lua"]:310: in function <.../HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua:293>
[string "@HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0-22.lua"]:340: in function <.../HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua:339>

**Comment by Krovikan** [comment]
Thanks for the reports. Will be fixed soon in the next release.

Regards
