### ISSUE TITLE
Error Spam in Valdrakken

### ISSUE THREAD

**Issue by OldWorldRaiders** [zarillion/handynotes-plugins#243]
14x HandyNotes_Dragonflight/core/nodes.lua:226: bad argument #1 to 'ipairs' (table expected, got function)
[string "=[C]"]: in function `ipairs'
[string "@HandyNotes_Dragonflight/core/nodes.lua"]:226: in function `Prepare'
[string "@HandyNotes_Dragonflight/core/map.lua"]:161: in function `Prepare'
[string "@HandyNotes_Dragonflight/core/core.lua"]:213: in function <HandyNotes_Dragonflight/core/core.lua:202>
[string "=(tail call)"]: ?
[string "@HandyNotes/HandyNotes.lua"]:443: in function <HandyNotes/HandyNotes.lua:429>
[string "=[C]"]: ?
[string "@HandyNotes/HandyNotes.lua"]:56: in function <HandyNotes/HandyNotes.lua:51>
[string "@HandyNotes/HandyNotes.lua"]:493: in function `?'
[string "@Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0-22.lua"]:310: in function <.../HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua:293>
[string "@HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0-22.lua"]:340: in function <.../HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua:339>

**Comment by Dathwada** [comment]
Closed, as this is the third open issue for this and will be fixed in the next version. [#241] [#242]
