### ISSUE TITLE
HandyNotes_Dragonflight, new error after today's update.

### ISSUE THREAD

**Issue by mhochradel** [zarillion/handynotes-plugins#244]
Message: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:226: bad argument #1 to 'ipairs' (table expected, got function)
Time: Fri Dec  9 10:59:16 2022
Count: 5
Stack: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:226: bad argument #1 to 'ipairs' (table expected, got function)
[string "=(tail call)"]: ?
[string "=[C]"]: in function `ipairs'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/nodes.lua"]:226: in function `Prepare'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/map.lua"]:161: in function `Prepare'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/core.lua"]:213: in function <...terface/AddOns/HandyNotes_Dragonflight/core/core.lua:202>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:443: in function `UpdateMinimapPlugin'
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:502: in function `?'
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/core.lua"]:261: in function `RefreshImmediate'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/core.lua"]:256: in function <...terface/AddOns/HandyNotes_Dragonflight/core/core.lua:254>

Locals: <none>

**Comment by Krovikan** [comment]
You mean v16? Is released recently (5 minutes ago).

**Comment by mhochradel** [comment]
Yes.  Today's update.  I'm actively getting errors like the above while playing with the update from today (per curseforge client) right now.

EDIT: No, v15.  Helps if I trust but verify myself in Curseforge.

**Comment by Dathwada** [comment]
@Krovikan No he does not, because Curseforge has to approve it first.

**Comment by mhochradel** [comment]
> @Krovikan No he does not, because Curseforge has to approve it first.

He's correct.  The update said "released today".  I know better, and apologize for the confusion.

**Comment by Krovikan** [comment]
@mhochradel when Cursorge approves, you see the recently v16 with the fix.

Regards

**Comment by Dathwada** [comment]
@mhochradel The problem is fixed and has been released in v16. In a couple of minutes you should be able to download it.
