### ISSUE TITLE
Error in Dragonflight Core after latest update

### ISSUE THREAD

**Issue by Masher76** [zarillion/handynotes-plugins#245]
I am getting the following error after updating to the latest version HandyNotes_Dragonmflightv15. 

20x HandyNotes_Dragonflight/core/nodes.lua:226: bad argument #1 to 'ipairs' (table expected, got function)
[string "=[C]"]: in function `ipairs'
[string "@HandyNotes_Dragonflight/core/nodes.lua"]:226: in function `Prepare'
[string "@HandyNotes_Dragonflight/core/map.lua"]:161: in function `Prepare'
[string "@HandyNotes_Dragonflight/core/core.lua"]:213: in function <HandyNotes_Dragonflight/core/core.lua:202>
[string "=(tail call)"]: ?
[string "@HandyNotes/HandyNotes.lua"]:443: in function <HandyNotes/HandyNotes.lua:429>
[string "=[C]"]: ?
[string "@HandyNotes/HandyNotes.lua"]:56: in function <HandyNotes/HandyNotes.lua:51>
[string "@HandyNotes/HandyNotes.lua"]:493: in function `?'
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0-22.lua"]:310: in function <.../HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua:293>
[string "@HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0-22.lua"]:340: in function <.../HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua:339>

**Comment by Krovikan** [comment]
Hello. Is fixed with the v16 release, online from 30 minutes ago.

Regards
