### ISSUE TITLE
Incinsistent Macro Incompatibility in Town areas

### ISSUE THREAD

**Issue by squish88** [zarillion/handynotes-plugins#247]
**Version:**  

HandyNotes_Dragonflight-v16.zip

**Issue Description:**

When I click on the button to run this simple macro in Valdrakken (and the Darkmoon Faire area):

#showtooltip Heroic Leap
/cast [@cursor] Heroic Leap

I get a message that says:
"HandyNotes_Dragonflight has been blocked from an action only available to the Blizzard UI.  You can disable this addon and reload the UI."

I disable the addon, and the macro works fine.  I will say it's super inconsistent as well (yay...),  I disabled it in the Darkmoon Faire, then hearthed back to Valdrakken and turned it back in to test it, and then was able to trigger the macro w/no issue... 

I'm sure you'll probably close this as "non-reproducable", but I've run into it a few times randomly so thought I'd give the heads up anyway in case it's somethin' obvious/"easy" on your end...

**Comment by zarillion** [comment]
This is part of an ongoing effort to reduce UI taint from the addon. We recently switched to LibUIDropDownMenu to help. Someone else pointed me at an addon library called Taintless which I'm going to investigate. I'll close for now but thanks for the additional report that there are still lingering taint issues.
