### ISSUE TITLE
"Blocked from an action only available to the Blizzard UI"

### ISSUE THREAD

**Issue by BevansDesign** [zarillion/handynotes-plugins#252]
**ADDON VERSION**: v19

**Describe the bug**
A popup message saying "HandyNotes_Dragonflight has been blocked from an action only available to the Blizzard UI". The two choices are to Disable the mod or Ignore the error. However, the error pops up each time I use a keyboard key to activate an ability. It doesn't happen when I click an ability with my mouse though.

I haven't yet figured out what triggers this, but I do know that hitting the Ignore button doesn't solve the issue. Reloading the UI fixes it for a while though.

**Comment by ghost** [comment]
@BevansDesign Make sure you update to v22 (most current version on CurseForge, etc.). I believe our team was able to get this bug squashed.
