### ISSUE TITLE
[Suggestion/Clarification] Primal Bear Cub tooltip

### ISSUE THREAD

**Issue by Slackluster** [zarillion/handynotes-plugins#254]
If it's not too much trouble, clarifying the last bit of this explanation to say you need to have the Honorary Dryad title equipped would be add a bit of clarity. Because the note talks about the Worldbreaker title right before mentioning equipping "the title," so I was actually confused and misunderstood which title needed to be equipped.

![image](https://user-images.githubusercontent.com/29845810/207898919-b3730f2f-511c-4e9e-aee5-f98a137e97d6.png)

**Comment by Krovikan** [comment]
Thanks for the report. In the next release will be fixed.


Regards
