### ISSUE TITLE
Magic Bound Chests Added

### ISSUE THREAD

**Issue by VioletFigueroa** [zarillion/handynotes-plugins#256]
https://www.wowhead.com/object=376426/magic-bound-chest#comments

**Comment by Ioney** [comment]
can you confirm that Anomaly Detection Mark I needed to see them? i have not yet played enough to reach renown 16 to check myself.

it was mentioned on wowhead: https://www.wowhead.com/spell=382499/anomaly-detection-mark-i#comments

**Comment by Krovikan** [comment]
Magic Bound feature is ready in the new v25 version.


Regards
