### ISSUE TITLE
Profession Treasures stay on map after collecting

### ISSUE THREAD

**Issue by MSav93** [zarillion/handynotes-plugins#259]
**ADDON VERSION**: v27 + previous versions

**Describe the bug**
Icons for Leatherworking items not disappearing after picking them up. E.g. Spare Djaradin Tools in The Waking Shores.
They seem to disappear for other professions / alts.

Note: I picked these items up before this addon had been updated to include them. That might contribute to the issue?

**Screenshots**
![image](https://user-images.githubusercontent.com/5080453/210118883-84745e1c-dd9b-4aea-ae54-1ef5756d0446.png)

**Comment by cremor** [comment]
Some Blacksmithing items also don't disappear, e.g. the one on the island in Ohn'ahran Plains.

**Comment by Dathwada** [comment]
We are still missing some hidden quest IDs for these treasures. That's the reason why they don't disappear.

**Comment by adavak** [comment]
all done and wait for next release.

**Comment by Krovikan** [comment]
v28 is out. In some minutes (depends of Curseforge) the new release will be ready to download.

Regards
