### ISSUE TITLE
Error: attempt to concatenate local 'mapID' (a table value)

### ISSUE THREAD

**Issue by Dairyman** [zarillion/handynotes-plugins#261]
Error: 
```
233x ...rfaceHandyNotes_Dragonflight/core/groups.lua:62: attempt to concatenate local 'mapID' (a table value)
```
https://github.com/zarillion/handynotes-plugins/blob/2da233c18694ff5a54e4483374c15e2395e8b525/plugins/10_Dragonflight/common.lua#L1006

`Group:GetDisplay()`: excepts a mapID not the map object.

**Comment by zarillion** [comment]
Nice find. It looks like this is only hit when the "Use map settings" option is enabled, so I missed it. Will get it fixed for the next release.

**Comment by Krovikan** [comment]
v29 is out with the fix. In some minutes (depends of Curseforge) it will be on line for download.

Regards
