### ISSUE TITLE
[HandyNotes: Dragonflight] Settings don't adhere to profiles

### ISSUE THREAD

**Issue by Slackluster** [zarillion/handynotes-plugins#265]
Hello. I recently noticed that when I change any of the filtering options for what appears on the map on one profile, this also alters those settings on another profile. That, of course, kind of defeats the purpose of having profiles.

**Comment by Ioney** [comment]
The Profile options in the HandyNotes Addon just saves the activated plugins, not the contents and options of those plugins.

We dont plan to implement profile support to our HN plugins.

**Comment by Slackluster** [comment]
Considering you can enable or disable the individual plugins per character, by enabling or disabling the corresponding addons, the profiles don't actually support any unique feature at all then. Seems very superfluous to even support profiles at that point, but thanks for the clarification. :)
