### ISSUE TITLE
Treasure Bug

### ISSUE THREAD

**Issue by Pyzam** [zarillion/handynotes-plugins#266]
**ADDON VERSION**: 10.0.2

**Describe the bug**
The addon shows 2 Emerald Gardens Explorer's Notes, when 1 of them is supposed to display "Ruby Gem Cluster"

Here are the ID's Ruby Gem Cluster is associated with.

Quest flagged when used: 70528

Quest flagged when looted: 70598

**Screenshots**
![Bug proof](https://user-images.githubusercontent.com/70659484/211203562-632744a9-5ffd-4cf8-972b-4f689a256666.jpg)

**Comment by Dathwada** [comment]
You are using HandyNotes: Dragonflight Treasures and not our plugin, please report it to them.

And by the way `10.0.2` is the game clients version and not the version of the addon you're using. This could be v41 or older.
