### ISSUE TITLE
Azure Span crafting icons have nil quest IDs

### ISSUE THREAD

**Issue by Protuhj** [zarillion/handynotes-plugins#267]
**ADDON VERSION**: Dragonflight v29

**Describe the bug**

These makes it so the icon will continue showing even if the knowledge has already been obtained.

---  

https://github.com/zarillion/handynotes-plugins/blob/master/plugins/10_Dragonflight/zones/azure_span.lua#L697  
Inscription (Lydiara) quest ID should be `70254`  

---  

https://github.com/zarillion/handynotes-plugins/blob/master/plugins/10_Dragonflight/zones/azure_span.lua#L707  
Jewelcrafting (Pluutar) quest ID should be `70255`

**Comment by Ioney** [comment]
Thanks for the report. I have added the Quest IDs to the nodes.
