### ISSUE TITLE
Feature Request: Checkmark next to completed achievement submenus?

### ISSUE THREAD

**Issue by Protuhj** [zarillion/handynotes-plugins#268]
In the dropdown for Achievements, there's no distinction for completed achievements.

It would be nice if there was a quick way to determine if the achievement is completed, either by mousing over the achievement, or just on the menu item for the achievement itself.

Extra points for distinguishing between account-completed and completed on the current character, since some achievement criteria come with reputation rewards.

**Comment by Ioney** [comment]
i implemented checkmarks to the Achievement submenu.
it should work like this:
Gray = Incomplete
Yellow = Completed on other character
Green = Completed by current character
![image](https://user-images.githubusercontent.com/4973036/212764105-b7eff6b0-4368-4c9f-ba07-3c50282936fd.png)

we still need to test it, i dont have an alt right now to test it myself.
if everything works it will get added to the next release.

**Comment by Protuhj** [comment]
~~What's the process to test a branch?~~

Oh, you committed to master. I'll clone the repo and test it out.

**Comment by Protuhj** [comment]
Seems to work great and is exactly what I was looking for.

Though, if an achievement isn't complete at all, I think it would be better with no check at all.

![image](https://user-images.githubusercontent.com/1165219/213796682-9db06f43-936e-49e3-a2a8-1f89b09c9f98.png)

The gray icon doesn't add information, and looks too close to the yellow ones IMO.

**Comment by ghost** [comment]
I wonder if it would be beneficial (or is even possible) to change from yellow checkmarks to blue checkmarks for tracking account-wide achievements completed. I imagine using the same blue as the blue used for [account-wide achievements](https://static.wikia.nocookie.net/wowpedia/images/7/7a/SsAchievements6.jpg/revision/latest?cb=20180825102209).

I do agree that removing the gray checkmark makes sense and simplifies for the viewer, regardless of changing to blue.

**Comment by Ioney** [comment]
this is now implemented in the latest v30 release
