### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#269]
Hover over elemental storm in obsidian hold - spams constantly:

33x HandyNotes_Dragonflight/common.lua:1027: attempt to index field '?' (a nil value)
[string "@HandyNotes_Dragonflight/common.lua"]:1027: in function <HandyNotes_Dragonflight/common.lua:1018>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `TryShowTooltip'
[string "@Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua"]:120: in function <...zzard_SharedMapDataProviders/AreaPOIDataProvider.lua:113>

Locals:
self = Frame {
 0 = <userdata>
 GetGlobalPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:310
 PanTo = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:317
 owningMap = FlightMapFrame {
 }
 zoomedInNudge = 0.250000
 UseFrameLevelType = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:422
 GetNudgeSourceZoomedInMagnitude = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:232
 SetScaleStyle = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:358
 GetNudgeSourcePinZoomedInNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:268
 UpdateTooltip = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:118
 GetMap = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:256
 OnCanvasSizeChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:336
 ApplyCurrentPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:393
 areaPoiID = 7221
 IsIgnoringGlobalPinScale = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:344
 GetHighlightType = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:98
 endScale = 1.200000
 HighlightTexture = Texture {
 }
 OnMouseEnter = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:113
 pinTemplate = "FlightMap_AreaPOIPinTemplate"
 OnMouseUp = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:177
 OnAcquired = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:72
 PanAndZoomTo = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:322
 ApplyCurrentAlpha = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:414
 OnLoad = <function> defined @Blizzard_FlightMap/FM_AreaPOIDataProvider.lua:10
 TryShowTooltip = <function> defined =[C]:-1
 pinFrameLevel = "PIN_FRAME_LEVEL_AREA_POI"
 OnReleased = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:147
 startAlpha = 1
 description = "A Primalist thunderstorm buffets Nokhudon Hold, imbuing creatures with new powers and strengths."
 ClearNudgeSettings = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:198
 OnCanvasPanChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:332
 OnMouseLeave = <function> defined =[C]:-1
 SetNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:285
 GetNudgeSourcePinZoomedOutNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:264
 startScale = 1
 OnClick = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:151
 Texture = Texture {
 }
 GetNudgeSourceRadius = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:219
 shouldGlow = false
 GetPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:305
 OnCanvasScaleChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:327
 normalizedY = 0.527564
 normalizedX = 0.357383
 GetNudgeTargetFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:211
 GetFrameLevelType = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:427
 SetAlphaStyle = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:383
 SetScalingLimits = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:348
 pinFrameLevelType = "PIN_FRAME_LEVEL_AREA_POI"
 Cr

**Comment by Krovikan** [comment]
Hello.

Version of the addon?

Regards

**Comment by ghost** [comment]
HandyNotes_Dragonflight-v29

This error has been happening for a week or two at least, maybe more.
Unsure the cause.

**Comment by Ioney** [comment]
is it still happening if you deactivate all other addons except HandyNotes and HandyNotes: Dragonflight?

**Comment by Rezy942** [comment]
I will try and see if i can recreate it because it doesnt happen all the time, so i would have to play for a while without any addons 
I have a feeling its some interaction with other addons like leatrix maps perhaps

**Comment by ghost** [comment]
Tested with ONLY handynotes + handynotes dragonflight + bugsack + buggrabber
I can reproduce the bug easily by talking to flight path NPC in valdraken and hovering over the elemental storm icon in any zone
Hope you can find a fix for this. THnaks

![image](https://user-images.githubusercontent.com/122007087/212474662-baae3f56-46aa-4d28-b997-c76d6a85df68.png)


64x HandyNotes_Dragonflight/common.lua:1027: attempt to index field '?' (a nil value)
[string "@HandyNotes_Dragonflight/common.lua"]:1027: in function <HandyNotes_Dragonflight/common.lua:1018>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `TryShowTooltip'
[string "@Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua"]:120: in function <...zzard_SharedMapDataProviders/AreaPOIDataProvider.lua:113>

Locals:
self = Frame {
 0 = <userdata>
 GetGlobalPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:310
 PanTo = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:317
 owningMap = FlightMapFrame {
 }
 zoomedInNudge = 0.250000
 UseFrameLevelType = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:422
 GetNudgeSourceZoomedInMagnitude = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:232
 SetScaleStyle = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:358
 GetNudgeSourcePinZoomedInNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:268
 UpdateTooltip = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:118
 GetMap = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:256
 OnCanvasSizeChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:336
 ApplyCurrentPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:393
 areaPoiID = 7221
 IsIgnoringGlobalPinScale = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:344
 GetHighlightType = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:98
 endScale = 1.200000
 HighlightTexture = Texture {
 }
 OnMouseEnter = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:113
 pinTemplate = "FlightMap_AreaPOIPinTemplate"
 OnMouseUp = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:177
 OnAcquired = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:72
 PanAndZoomTo = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:322
 ApplyCurrentAlpha = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:414
 OnLoad = <function> defined @Blizzard_FlightMap/FM_AreaPOIDataProvider.lua:10
 TryShowTooltip = <function> defined =[C]:-1
 pinFrameLevel = "PIN_FRAME_LEVEL_AREA_POI"
 OnReleased = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:147
 startAlpha = 1
 description = "A Primalist thunderstorm buffets Nokhudon Hold, imbuing creatures with new powers and strengths."
 ClearNudgeSettings = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:198
 OnCanvasPanChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:332
 OnMouseLeave = <function> defined =[C]:-1
 SetNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:285
 GetNudgeSourcePinZoomedOutNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:264
 startScale = 1
 OnClick = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:151
 Texture = Texture {
 }
 GetNudgeSourceRadius = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:219
 shouldGlow = false
 GetPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:305
 OnCanvasScaleChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:327
 normalizedY = 0.527564
 normalizedX = 0.357383
 GetNudgeTargetFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:211
 GetFrameLevelType = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:427
 SetAlphaStyle = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:383
 SetScalingLimits = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:348
 pinFrameLevelType = "PIN_FRAME_LEVEL_AREA_POI"
 Cr

**Comment by Dairyman** [comment]
Problem is the flight map shows the Storms and uses the mapID `2057` which is not listed in `ELEMENTAL_STORM_MOB_ACHIVEMENTS`. Plus to support the flight map correctly would need to associate the `areaPoiID` to the zones they belong too.

**Comment by ghost** [comment]
So the easiest fix would be `if stormType and not mapID == 2057 and group:GetDisplay(mapID) then` that would just disable the Elemental Storm integration on the Dragon Isles flight/continent map.

The alternate fix would be to add mapIDs to `ELEMENTAL_STORM_AREA_POIS` and do some more checking.

**Comment by Ioney** [comment]
```lua
if stormType and not FlightMapFrame:IsShown() and group:GetDisplay(mapID) then 
```
is probably a more general solution

**Comment by Corefanatik** [comment]
Hi .is there an fix for this  in work? its the only lua error  that  i had for some weeks now. or I disable it before I get too used to it now. ;)

**Comment by ghost** [comment]
@Corefanatik yes, this will be fixed in the next release!

**Comment by Corefanatik** [comment]
nice nice ;)
thx for the quick response.good day all.

**Comment by ghost** [comment]
Thank you for getting on top of this so quick!

**Comment by Corefanatik** [comment]
Closed?? im on lua error 1596 ;)

1596x HandyNotes_Dragonflight/common.lua:1027: attempt to index field '?' (a nil value)
[string "@HandyNotes_Dragonflight/common.lua"]:1027: in function <HandyNotes_Dragonflight/common.lua:1018>
[string "=[C]"]: in function `TryShowTooltip'
[string "@Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua"]:120: in function <...zzard_SharedMapDataProviders/AreaPOIDataProvider.lua:113>

Locals:
self = Frame {
 0 = <userdata>
 GetGlobalPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:310
 PanTo = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:317
 owningMap = FlightMapFrame {
 }
 zoomedInNudge = 0.250000
 UseFrameLevelType = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:422
 GetNudgeSourceZoomedInMagnitude = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:232
 SetScaleStyle = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:358
 GetNudgeSourcePinZoomedInNudgeFactor = <function> defined @Blizzard_MapCanvas/
MapCanvas_DataProviderBase.lua:232
 SetScaleStyle = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:358
 GetNudgeSourcePinZoomedInNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:268
 UpdateTooltip = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:118
 GetMap = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:256
 OnCanvasSizeChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:336
 ApplyCurrentPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:393
 areaPoiID = 7254
 IsIgnoringGlobalPinScale = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:344
 GetHighlightType = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:98
 endScale = 1.200000
 HighlightTexture = Texture {
 }
 OnMouseEnter = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:113
 pinTemplate = "FlightMap_AreaPOIPinTemplate"
 OnMouseUp = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:177
 OnAcquired = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:72
 PanAndZoomTo = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:322
 ApplyCurrentAlpha = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:414
 OnLoad = <function> defined @Blizzard_FlightMap/FM_AreaPOIDataProvider.lua:10
 TryShowTooltip = <function> defined =[C]:-1
 pinFrameLevel = "PIN_FRAME_LEVEL_AREA_POI"
 OnReleased = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:147
 startAlpha = 1
 description = "Ein Sandsturm der Primalisten hüllt den Schlackensumpf ein und erfüllt Kreaturen mit neuer Macht und Kräften."
 ClearNudgeSettings = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:198
 OnCanvasPanChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:332
 OnMouseLeave = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:174
 SetNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:285
 GetNudgeSourcePinZoomedOutNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:264
 startScale = 1
 OnClick = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:151
 Texture = Texture {
 }
 GetNudgeSourceRadius = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:219
 shouldGlow = false
 GetPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:305
 OnCanvasScaleChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:327
 normalizedY = 0.349469
 normalizedX = 0.434018
 GetNudgeTargetFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:211
 GetFrameLevelType = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:427
 SetAlphaStyle = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:383
 SetScalingLimits = <function> defined @Blizzard_MapCanvas/

**Comment by Krovikan** [comment]
Hello:

The Collaborator close the Issue because the fix is working well in our test. Only remains release the v30 asap.

Regards

**Comment by Ioney** [comment]
reopened to inform everybody that it is fixed in v30 which will be released asap.

**Comment by Ioney** [comment]
v30 is now released.
