### ISSUE TITLE
Relocate slightly ancient protector rare icon

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#270]
**ADDON VERSION**: (place version of the addon you have installed here)
HandyNotes_Dragonflight-v29

**Describe the bug**
When elemental storm is up in this area, it is extremely hard to see it because of rare icon
It would be great if rare icon was shifted sideways slightly
I literally had to go to flight path map to find where that 2nd storm was. I really wish there was a feature to show all this stuff on the continent map. Perhaps an idea for handy notes?
![image](https://user-images.githubusercontent.com/122007087/213453532-280422fd-64d2-4eae-95d5-fb6b46d1fb93.png)

**Screenshots**

**Comment by adavak** [comment]
v30 relocated.
