### ISSUE TITLE
Saw this today up on Live.  Sent to WUTNAME(Spartanui) 

### ISSUE THREAD

**Issue by lectrcsprx** [zarillion/handynotes-plugins#271]
**AD88x Usage: local itemLink = C_Item.GetItemLinkByGUID(itemGUID)
[string "=[C]"]: in function `GetItemLinkByGUID'
[string "@SpartanUI/modules/Tooltips.lua"]:157: in function <SpartanUI/modules/Tooltips.lua:152>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "@HandyNotes_DragonflightTreasures/handler/handler.lua"]:967: in function <...HandyNotes_DragonflightTreasures/handler/handler.lua:785>
[string "=(tail call)"]: ?
[string "@HandyNotes_DragonflightTreasures/handler/handler.lua"]:1042: in function <...HandyNotes_DragonflightTreasures/handler/handler.lua:1018>
[string "=[C]"]: ?
[string "@HandyNotes/HandyNotes.lua"]:56: in function <HandyNotes/HandyNotes.lua:51>
[string "@HandyNotes/HandyNotes.lua"]:166: in function `OnEnter'
[string "@HandyNotes/HandyNotes.lua"]:399: in function <HandyNotes/HandyNotes.lua:398>

Locals:
(*temporary) = "Usage: local itemLink = C_Item.GetItemLinkByGUID(itemGUID)"DON VERSION**: (place version of the addon you have installed here)

**Describe the bug**
A clear and concise description of what the bug is and how to reproduce it.

**Screenshots**

**Comment by Krovikan** [comment]
> [string "=(tail call)"]: ? [string "@`HandyNotes_DragonflightTreasures`/handler/handler.lua"]:967: in function <...`HandyNotes_DragonflightTreasures`/handler/handler.lua:785> [string "=(tail call)"]: ? [string "@`HandyNotes_DragonflightTreasures`/handler/handler.lua"]:1042: in function <...`HandyNotes_DragonflightTreasures`/handler/handler.lua:1018> 

Sorry, but is not our addon. You are using HandyNotes_DragonflightTreasures and ours is called Handynotes: Dragonflight.

Regards
