### ISSUE TITLE
Bug? Dragonriding races icons not showing up.

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#273]
**ADDON VERSION**: (place version of the addon you have installed here)
v30

**Describe the bug**
Not sure if bug or im missing something...
Trying to track down missing Gold reverse courses
Hoped to click on track races but none of them are showing up
Ideally this should show all race locations on the map, irrelevant of their achievement status

Thank you

**Screenshots**
![image](https://user-images.githubusercontent.com/122007087/215241203-2a73d821-a8f3-4042-b89a-4e0e9ddc0f74.png)

**Comment by Krovikan** [comment]
Hello:

The time for Reverse Courses was commited yesterday (2 days after v30).

Until the v31 release will not available.

Regards

**Comment by Ioney** [comment]
If you completed all the race achievements, the node for the race will be hidden. You need to enable the "Show complete" option and they should appear again.

The reverse races will be added in v31.

**Comment by ghost** [comment]
Thank you so much, i didnt realize this.
Looking forward to reverse races :)

**Comment by Krovikan** [comment]
v31 is out! :)

**Comment by ghost** [comment]
Amazing thank you
