### ISSUE TITLE
Quackers Rare Duck Trap Kit required materials have changed 

### ISSUE THREAD

**Issue by Protuhj** [zarillion/handynotes-plugins#275]
**ADDON VERSION**: (place version of the addon you have installed here)
v30

Tooltip is now: [Use: Combine with 1 Large Sturdy Femur, 3 Contoured Fowlfeathers, and 2 Tallstrider Sinew to create an Aylaag Duck Trap.](https://www.wowhead.com/spell=377752/build-trap)

**Comment by Ioney** [comment]
thanks for the report, i changed the item id's.
