### ISSUE TITLE
Nazjatar is broken

### ISSUE THREAD

**Issue by Vampire2008** [zarillion/handynotes-plugins#276]
**ADDON VERSION**: HandyNotes_BattleForAzeroth-v13.zip

**Describe the bug**
Go to Nazjatar. And see that no marks available.

**Comment by adavak** [comment]
You need to complete several guide quests, which will not be displayed until you arrive at the camp.

**Comment by Vampire2008** [comment]
I am on characted that completed most of Nazjatar activities. Only few rares left. Story is fully completed.

**Comment by Vampire2008** [comment]
Before 10.0.5 update all works.

**Comment by Dathwada** [comment]
I can't see any issues when I'm in Nazjatar.
Rares, treasures and all the other stuff is displayed on my map.

Do you have enabled the Addons `HandyNotes` and `Handynotes: Battle for Azeroth`?
Do you have enabled `Load out of date AddOns`? (HandyNotes itself isn't updated for 10.0.5)

**Comment by Vampire2008** [comment]
Addon is enabled. And I see marks on other Battle for Azeroth locations.

**Comment by Vampire2008** [comment]
![](https://img-host.ru/9aUjV.png)

**Comment by Dathwada** [comment]
That is weird. Do you have tried to reinstall the addon ?

**Comment by Vampire2008** [comment]
Tried. Not work. Tried also delete data.
Maybe something with localization?

**Comment by adavak** [comment]
Reproduce error:

10 lvl alts, no BfA expansion quest logged.
looking the Nazjatar map got nothing.

https://github.com/zarillion/handynotes-plugins/commit/de9c5f96ad9be443b35a8f6e34243d3c9bee848a

```ns.faction``` to ```UnitFactionGroup('player')```

worked fine.

It appears to be an issue with the load order.

**Comment by Ioney** [comment]
I cant replicate the error, also changed my client to russian.
both v13 and internal versions work perfect for me.

Deactivate all addons except HandyNotes and Handynotes_BattleForAzeroth to make sure other addons arent causing it.
if its still not working rename your WTF folder to WTF_backup or something and try again.

**Comment by Ioney** [comment]
i found the problem.

@zarillion do you want to update the addon now or wait for me to add the Safari to BfA and update it then?

**Comment by adavak** [comment]
update the file and tested,

still not working.

press ctrl+alt force display all note, the guide ! icon show up horde icon, (im using alliance alts).

**Comment by Vampire2008** [comment]
> Deactivate all addons except HandyNotes and Handynotes_BattleForAzeroth to make sure other addons arent causing it. if its still not working rename your WTF folder to WTF_backup or something and try again.

Still not working.

**Comment by adavak** [comment]
replace `zones/nazjatar.lua` line 51

```lua
if ns.faction == 'Alliance' then
```

to

```lua
if UnitFactionGroup('player') == 'Alliance' then
```

temporary fix problem.

**Comment by Vampire2008** [comment]
On Horde Nazjatar works. On Alliance not.

**Comment by Dathwada** [comment]
With my fix you'll now be able to see a yellow ! on the Nazjatar map with instructions on what you're missing from the intro questline.

**Comment by Krovikan** [comment]
v14 is out! :)
