### ISSUE TITLE
Feature Request: Djardin caches & any other similar chests (if any?)

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#277]
Hello,

Currently I dont see option to show Djardin caches in Waking Shores in order to farm them
AllTheThings shows that there are many set pieces & transmog pieces to collect!
Would be great if you could consider it :)
Coordinates already provided here: https://www.wowhead.com/object=376580/djaradin-cache#comments

ty!

**Comment by Krovikan** [comment]
v31 is out! :)
