### ISSUE TITLE
Error when mousing over elemental storms

### ISSUE THREAD

**Issue by tommy610** [zarillion/handynotes-plugins#278]
**ADDON VERSION**: (place version of the addon you have installed here)
v30

**Describe the bug**
When on the zoomed out map showing all of dragonflight, mousing over the elemental storms brings up this error

**Screenshots**
157x HandyNotes_Dragonflight/common.lua:1093: attempt to index field '?' (a nil value)
[string "@HandyNotes_Dragonflight/common.lua"]:1093: in function <HandyNotes_Dragonflight/common.lua:1083>
[string "=[C]"]: in function `TryShowTooltip'
[string "@Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua"]:120: in function <...zzard_SharedMapDataProviders/AreaPOIDataProvider.lua:113>

Locals:
self = Frame {
 0 = <userdata>
 GetGlobalPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:310
 PanTo = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:317
 owningMap = WorldMapFrame {
 }
 UseFrameLevelType = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:422
 GetNudgeSourceZoomedInMagnitude = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:232
 SetScaleStyle = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:358
 GetNudgeSourcePinZoomedInNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:268
 UpdateTooltip = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:118
 GetMap = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:256
 OnCanvasSizeChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:336
 ApplyCurrentPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:393
 areaPoiID = 7256
 IsIgnoringGlobalPinScale = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:344
 GetHighlightType = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:98
 endScale = 1.200000
 HighlightTexture = Texture {
 }
 OnMouseEnter = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:113
 pinTemplate = "AreaPOIPinTemplate"
 OnMouseUp = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:177
 OnAcquired = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:72
 PanAndZoomTo = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:322
 ApplyCurrentAlpha = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:414
 OnLoad = <function> defined @Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua:9
 TryShowTooltip = <function> defined =[C]:-1
 pinFrameLevel = "PIN_FRAME_LEVEL_AREA_POI"
 OnReleased = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:147
 startAlpha = 1
 description = "A Primalist snowstorm chills the Slagmire, imbuing creatures with new powers and strengths."
 ClearNudgeSettings = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:198
 OnCanvasPanChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:332
 SetNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:285
 GetNudgeSourcePinZoomedOutNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:264
 endAlpha = 1
 startScale = 1
 OnClick = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:151
 Texture = Texture {
 }
 GetNudgeSourceRadius = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:219
 alphaFactor = 1
 OnMouseLeave = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:174
 shouldGlow = false
 GetPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:305
 GetNudgeTargetFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:211
 GetFrameLevelType = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:427
 SetAlphaStyle = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:383
 SetScalingLimits = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:348
 OnCanvasScaleChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:327
 CreateSubPin = <function> de

**Comment by Ioney** [comment]
you mean the normal map, not the flight map?

the storms dont show up on my map when im on the dragonisle map.

**Comment by tommy610** [comment]
yes, the regular map that shows all 4 zones. maybe i have an addon showing the storms, shrug

**Comment by Ioney** [comment]
which addons do you use besides HandyNotes: Dragonflight that modifies the map?

try to disable all addons except HandyNotes and HandyNotes: Dragonflight.

**Comment by Ioney** [comment]
did v31 fix it for you or is it still bugging?

**Comment by tommy610** [comment]
Sorry for the slow response. I still get the errors, but also the errors are because of the addon Better World Quests. When I disable this addon, it doesn't show the storm icons on the world map showing all four zones. So there is nothing to mouse over to have the error pop up. With the addon it shows the storm icon on the map, thus mousing over the icon causes the error.

**Comment by ghost** [comment]
@tommy610  This will be fixed in the next release

**Comment by tommy610** [comment]
Thank you! Glad we were able to figure this out.
