### ISSUE TITLE
Note addition request: Iskaara Feast weekly possible rewards

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#279]
Hello,

Similar to my previous post about Djardin caches - I would love to have an icon dedicated to checking which rewards iskaara feast gives in the weekly box. Similar to this:
![image](https://user-images.githubusercontent.com/122007087/216754226-158f0cfc-d9e1-44dc-b23c-dc416718a089.png)

I think would be great as there is no other easy way to see it unless going to wowhead, and even then - what is the bag name??
Some cooking recipes can only be received from this feast - so this can be useful for those collectors out there like myself

Thanks!

**Comment by adavak** [comment]
https://www.wowhead.com/item=198131/recipe-grals-devotion
https://www.wowhead.com/item=198129/recipe-grals-reverence
https://www.wowhead.com/item=198130/recipe-grals-veneration

you mean this 3 recipe of cooking from weekly item?
https://www.wowhead.com/item=200095/supply-laden-soup-pot

**Comment by Krovikan** [comment]
If we are taking about cooking related items maybe also:

https://www.wowhead.com/item=200652

This item is exclusive of this weekly item.

Regards

**Comment by ghost** [comment]
> https://www.wowhead.com/item=198131/recipe-grals-devotion https://www.wowhead.com/item=198129/recipe-grals-reverence https://www.wowhead.com/item=198130/recipe-grals-veneration
> 
> you mean this 3 recipe of cooking from weekly item? https://www.wowhead.com/item=200095/supply-laden-soup-pot

Correct!
