### ISSUE TITLE
Note addition request: Glowing Arcane Jewel in Azure Span

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#280]
https://www.wowhead.com/item=200528/glowing-arcane-jewel#comments

Would be neat to add this as its technically a secret treasure that gives a quest for 2 manuscripts :)

**Comment by adavak** [comment]
Already added. Wait for next release.

**Comment by ghost** [comment]
Thank you!!

**Comment by Krovikan** [comment]
v31 is out! :)
