### ISSUE TITLE
Phenran is incorrectly marked as one of the rotational rares

### ISSUE THREAD

**Issue by Protuhj** [zarillion/handynotes-plugins#281]
Phenran isn't on the rotation, so the text about it being on the rotation should be removed from its node.

**Comment by ghost** [comment]
+1 i noticed this too

Its weird because Phenran is mentioned by many people to be a part of rotation but same time he is spawning regularly outside of it. He did not spawn for me when the time came for him to spawn during rotation cycle.

Also curious what spawns instead of him..

**Comment by Ioney** [comment]
Nothing spawns instead of gi. There is just a 1 hour gap.
