### ISSUE TITLE
Bug: error on storm tooltip in world map with addon "Better World Quests"

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#285]
**ADDON VERSION**: (place version of the addon you have installed here)
v31 handynotes DF

**Describe the bug**
As title says - handynotes throws bugs when hovering on icons created by better world quests
Can reproduce by enabling handynotes + handynotes DF + better world quests addon

**Screenshots**
![image](https://user-images.githubusercontent.com/122007087/219014476-371882c0-3b8f-4c8b-8f4d-e4c43ee62908.png)

79x HandyNotes_Dragonflight/common.lua:1132: attempt to index field '?' (a nil value)
[string "@HandyNotes_Dragonflight/common.lua"]:1132: in function <HandyNotes_Dragonflight/common.lua:1122>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `TryShowTooltip'
[string "@Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua"]:120: in function <...zzard_SharedMapDataProviders/AreaPOIDataProvider.lua:113>

Locals:
self = Frame {
 0 = <userdata>
 GetGlobalPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:310
 PanTo = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:317
 owningMap = WorldMapFrame {
 }
 UseFrameLevelType = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:422
 GetNudgeSourceZoomedInMagnitude = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:232
 SetScaleStyle = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:358
 GetNudgeSourcePinZoomedInNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:268
 UpdateTooltip = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:118
 GetMap = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:256
 OnCanvasSizeChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:336
 ApplyCurrentPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:393
 areaPoiID = 7246
 IsIgnoringGlobalPinScale = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:344
 GetHighlightType = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:98
 endScale = 1.200000
 HighlightTexture = Texture {
 }
 OnMouseEnter = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:113
 pinTemplate = "AreaPOIPinTemplate"
 OnMouseUp = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:177
 OnAcquired = <function> defined @Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua:72
 PanAndZoomTo = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:322
 ApplyCurrentAlpha = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:414
 OnLoad = <function> defined @Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua:9
 TryShowTooltip = <function> defined =[C]:-1
 pinFrameLevel = "PIN_FRAME_LEVEL_AREA_POI"
 OnReleased = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:147
 startAlpha = 1
 description = "A Primalist sandstorm engulfs Tyrhold, imbuing creatures with new powers and strengths."
 ClearNudgeSettings = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:198
 OnCanvasPanChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:332
 SetNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:285
 GetNudgeSourcePinZoomedOutNudgeFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:264
 endAlpha = 1
 startScale = 1
 OnClick = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:151
 Texture = Texture {
 }
 GetNudgeSourceRadius = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:219
 alphaFactor = 1
 OnMouseLeave = <function> defined =[C]:-1
 shouldGlow = false
 GetPosition = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:305
 GetNudgeTargetFactor = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:211
 GetFrameLevelType = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:427
 SetAlphaStyle = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:383
 SetScalingLimits = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:348
 OnCanvasScaleChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:327
 CreateSubPin = <function> defined @Blizzard_SharedMapDataProviders/SharedMapPoiTempla

**Comment by Ioney** [comment]
it will be fixed in the next version

see #278

**Comment by Krovikan** [comment]
I close this ticket for duplicate. Please see #278.
