### ISSUE TITLE
Icon adjustment request: Tuskaar Tacklebox & Djaradin Caches

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#291]
Hello,

Tacklebox & Djaradin Cache has same chest map icon as magic-bound chest. (so 3 treasures with same icons) I would love if both received its own unique icon - something similar to disturbed dirt, but different visually from the already existing DF map icons. 
Especially important for Tacklebox as some people (like me) want to stay away from them but cant due to blizz minimap code (i think). 
Handynotes can help with that by showing players where on map they are located. But icon needs to be visually different from rest.

Tacklebox:
![image](https://user-images.githubusercontent.com/122007087/219848388-cb6dcced-0c35-4597-8065-f24999037bfa.png)
Magic chest:
![image](https://user-images.githubusercontent.com/122007087/219848403-a6515ff2-4d97-42a4-a947-c3e397b8599a.png)
Djaradin cache:
![image](https://user-images.githubusercontent.com/122007087/219848422-c05ad597-e557-4e3c-909c-4bc1e7f967b9.png)

I hope this explains it well. Thank you.

**Comment by Ioney** [comment]
they already have different icon colors. there is no unique icon associated to them like the shovel to the disturbed dirt.

we could change it to yellow to make it more distinguishable
![grafik](https://user-images.githubusercontent.com/4973036/219904072-b7ea5a38-2af5-4b14-8909-a97a445cea18.png)

**Comment by ghost** [comment]
Ah yes, i just noticed the subtle differences but they are indeed subtle. On a large monitor with high resolution it is almost impossible to notice unless adjusting chest scales (which i like to keep at scale: 1).
If you change the colors of each chest, that would be neat.

To go 1 step forward, you could add a color picker option for user to select, together with scale and transparency :) That would be neat!

**Comment by Ioney** [comment]
If it were possible, which I'm not sure it is, the Wow API would tint the entire icon, not just the colored part of the treasure icon.

**Comment by ghost** [comment]
Hmm I see. So the only solution would be custom icons?
My problem is that these small color differences on default chest icons are extremely hard to see (for me & my monitor resolution at least).
Is it too much of a task to make custom chest icons manually colorized into distinctive red green blue etc. ? Instead of blizz ones.
They could be used for past and future expansions where treasure types vary so much like in Dragonflight.
You still keep all the current CUSTOM icons - but for random farmable "treasure chests" types of treasures, you could use those custom colorized icons instead.

Just brainstorming here. :)
