### ISSUE TITLE
Feature Request: add "Frostbound chest" locations

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#300]
Hello,

Similar to some recent additions - would it be useful to add Frostbound chests?
They also drop some collectable transmog items that can be sold on AH :)

Thank you!

https://www.wowhead.com/object=381041/frostbound-chest#contains

**Comment by Krovikan** [comment]
Hello, is in ToDo list. Not done yet.

Regards

**Comment by ghost** [comment]
Just wanted to add a quick note as I found a useful wowhead comment, there are 3 (or more) similar transmog chests.
Link: https://www.wowhead.com/object=381042/simmering-chest#comments
Im sure you're aware, but just thought id leave this here anyway :)
