### ISSUE TITLE
Wrong Lost Soul pet

### ISSUE THREAD

**Issue by Vampire2008** [zarillion/handynotes-plugins#301]
**ADDON VERSION**: v53

**Describe the bug**
For Shadowlands Safari achievment in Revendreth shown wrong pet Lost Soul.
It shows that [Lost Soul (id 150910)](https://www.wowhead.com/npc=150910). But that pet is not actually present in game.
Actual pet is that [Lost Soul (id 171123)](https://www.wowhead.com/npc=171123)

**Comment by Ioney** [comment]
thanks for submitting the bug, it will be fixed in the next version
