### ISSUE TITLE
Addon 

### ISSUE THREAD

**Issue by Imna1975** [zarillion/handynotes-plugins#307]
not a problem but a request if it is also possible addons for the other expansions would be possible pandaria legion and so on

**Comment by Krovikan** [comment]
Sometimes we do something for other expansions.

We have at Curse: HandyNotes: Shadowlands and HandyNotes: BfA.

We have done a lot for Legion and Warlords of Draenor, something for Pandaria and Cataclysm. But none finished and not released.

The focus is in the new expansion and, with free time, in others.

I hope that some coder add some more info. I summon to @zarillion , @Ioney and @wyldclaw .

Regards

**Comment by Ioney** [comment]
I'm now working on the missing Legion Rares/Treasures and then have to research what achievements and other things are worth adding.

Zarillion wants the plugins to be finished before releasing them .

**Comment by ghost** [comment]
I'm going to mark this as closed since the additional plugins are a work in progress right now
