### ISSUE TITLE
"30-minute rare" timers off by 8 hours.

### ISSUE THREAD

**Issue by Petrol30** [zarillion/handynotes-plugins#309]
I posted this on the main page but I should probably post it here:

The tooltip timers on the "30-minute rares" are all showing times 8 hours after their real spawn time.

Example: Broodweaver is spawning at 12pm server but the addon is shows next spawn time is 20:00 (8pm).

I'm playing on US realms and my local time and server time are both the same.

**Comment by ghost** [comment]
@Petrol30 I did some testing with a few rares and the time on the tooltip was correct. Which timezone are you playing in?

**Comment by Petrol30** [comment]
US Tichcondrius (PST)

**Comment by ghost** [comment]
@Petrol30 That is very weird. I play on US-Lightbringer (PST) and the tooltip/spawn time was correct for 3 rares in a row that I just tested.

**Comment by Petrol30** [comment]
I will post a screenshot of what I'm seeing here in a couple mins

**Comment by Petrol30** [comment]
https://i.imgur.com/l6X2V9h.jpg

**Comment by ghost** [comment]
@Petrol30 What version of HandyNotes: Dragonflight are you using?

**Comment by Ioney** [comment]
it seems there was a fix from @adavak shortly after the last release

@Petrol30 can you try to apply these changes to your local file and see if this fixes the timing?
https://github.com/zarillion/handynotes-plugins/commit/bee58e92dc141ed5f15befe25a1f82818ba357b2#diff-e635d0739fb2e182fb1258a6c5ad68a17bc5f7deba4fd83cecccca2020457866
https://github.com/zarillion/handynotes-plugins/commit/bee58e92dc141ed5f15befe25a1f82818ba357b2#diff-03c2cd16e0dbcee7e8aff533414efaaed2f5694e12e9c5ec2fd87089d239f264

**Comment by Petrol30** [comment]
I'm using V32

I just applied the changes above and can confirm that it fixed the timer issue with the rares.  

Thanks!

**Comment by Ioney** [comment]
i'm happy that this mystery is solved now.
i guess @zarillion will release the next version either when 10.0.7 goes live or shortly after.
