### ISSUE TITLE
got this LUA error on v13

### ISSUE THREAD

**Issue by hoolibas** [zarillion/handynotes-plugins#31]
Message: ...ace\AddOns\HandyNotes_Shadowlands\zones\icecrown.lua:87: bad argument #2 to 'strsplit' (string expected, got nil)
Time: Wed Nov 11 17:30:27 2020
Count: 79
Stack: ...ace\AddOns\HandyNotes_Shadowlands\zones\icecrown.lua:87: bad argument #2 to 'strsplit' (string expected, got nil)
[string "=(tail call)"]: ?
[string "=[C]"]: in function `strsplit'
[string "@Interface\AddOns\HandyNotes_Shadowlands\zones\icecrown.lua"]:87: in function <...ace\AddOns\HandyNotes_Shadowlands\zones\icecrown.lua:83>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by zarillion** [comment]
Give v14 a try. I believe 00c6df9ec4af159c5795214aceeabfa69101065a fixed this issue.
