### ISSUE TITLE
[solved] Bug/Missing data: Expedition Scout's Pack

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#310]
Edit* nevermind - did some testing and it is class-based rewards (even though tradeable cosmetic - please see below for suggestion) & feel free to close issue :)

Hello,

I know Dragonflight shared treasures are a pain but I noticed a loot drop that isnt shown on the minimap icon:

Icon reward list:
![image](https://user-images.githubusercontent.com/122007087/226234149-6ddfda5c-3686-4d15-8326-87fec98819ca.png)

Just received from scout pack:
![image](https://user-images.githubusercontent.com/122007087/226234196-a3cf3c08-2cd6-40bf-9388-91c9945fe492.png)

Perhaps this is a class requirement as I looted this on a DK that cannot wield staves?
If so, is there a way to toggle showing ALL rewards possible, even not wearable by my current class?
This is because these rewards are tradeable, so its nice to know that i can keep farming for my alts.

Thank you :)

**Comment by adavak** [comment]
The version you installed not new, please install the latest version.

https://github.com/zarillion/handynotes-plugins/releases/tag/10_Dragonflight-v33

**Comment by ghost** [comment]
I see, thank you for explanation.
I wish there was a place users can go to check this kind of stuff. ATT & handynotes do a GREAT job but still miss a lot of these weird shared collectibles.

I guess an icon at the edge of the screen that lists all the transmoggable collectibles would be too big of a project, would it?
Some form of an "overall" completion list, instead of relying on 300 different treasure chests, with items missing it many of them.

**Comment by ghost** [comment]
> The version you installed not new, please install the latest version.
> 
> https://github.com/zarillion/handynotes-plugins/releases/tag/10_Dragonflight-v33

That is the one I have, thats the version I used when I made this post
![image](https://user-images.githubusercontent.com/122007087/226240378-7ce0e456-da0f-4866-8d39-4956832b5133.png)

**Comment by adavak** [comment]
```lua
Transmog({item = 201388, slot = L['cosmetic']}), -- Dragonspawn Wingtipped Staff
```

Added very early, recommend reinstall it.

**Comment by ghost** [comment]
I did some testing and yes, the rewards are class-based
Here is a screenshot on my mage:
![image](https://user-images.githubusercontent.com/122007087/226242328-8ebacd78-c6f9-413f-947e-9871bc327cd9.png)

It does not show up on my DK.
Would it be a good idea to disable class requirements for tradeable cosmetic items like these?
I understand soulbound - but these are farmable and tradeable so it's good to see it on all characters :)
Although I also understand the problem with TOO many items in a list... which is where my idea of 1 icon at edge of screen to list ALL cosmetic collectables :)

**Comment by adavak** [comment]
`Show unobtainable transmog rewards`

toggle on this option.

**Comment by ghost** [comment]
Thank you so much! i feel so dumb. Looked at the settings many times but somehow missed that one.
