### ISSUE TITLE
Feature improvement: Elemental Storm tooltips on zone maps

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#316]
Hello,

Would it be possible (and worth doing) to add a bit more info to elemental storms?
The problem are the rares that are related to the storm type (like Gaelzion, Infernum, etc.) (NOT the ones related to the storm area)
Their loot is not shown on the storm icon, despite not being collected.
That leaves users to have to go through AllTheThings addon to track collection status.

PREFERRED SOLUTION: Show loot from these storm-type-related rares under their respective storm. (ex. Gaelzion loot under air storm icon on map). Also to go a step forward - addon can track collection of the 4 pieces to create heirloom trinket. For example if i have 3 out of 4 pieces in bank, addon should show on tooltip which ones are collected, and which ones are still missing. All of this would be huge QoL  :)

Here is example of my current tooltip of air storm:
![image](https://user-images.githubusercontent.com/122007087/229420148-32f0c8a8-8955-4fbf-bf69-07eca0c5ed11.png)

Example ATT mini-list in Azure Span air storm:
![image](https://user-images.githubusercontent.com/122007087/229420547-517c553f-22c7-4c44-aaf5-baafa33bae90.png)

Thank you so much!

**Comment by ghost** [comment]
Hello - was this already included in recent update?
I just tested it again and did not see bag of furious winds in the tooltip as drop from Gaelzion
(sorry if it wasnt)

Also on related note - enchanting illusions are shown as incomplete even though I learned them
![image](https://user-images.githubusercontent.com/122007087/236014102-7e13df7d-6468-48b8-919f-f2a7a9758f8d.png)

![image](https://user-images.githubusercontent.com/122007087/236014303-a19baf90-9eb6-4ec4-9114-34b5839ce6e0.png)

**Comment by ghost** [comment]
To add to this topic: 
![image](https://github.com/zarillion/handynotes-plugins/assets/122007087/02d45f02-5688-463e-81e4-495b6c03d616)

Something is definetely bugged with handynotes and storms. Any chance for confirmation that this is a known issue and coulld possibly be resolved?

Thanks :)

**Comment by Dathwada** [comment]
Hi, could you please test if there is this `Already known` text in the tooltip when you hover over the formula?

`/script DEFAULT_CHAT_FRAME:AddMessage("\124cff0070dd\124Hitem:200911::::::::70:::::\124h[Formula: Illusion: Primal Air]\124h\124r");`

For the Hilted Monolith:
It is possible that you already know this transmog from another item, but for ATT you don't have this transmog from this specific item, even if they're the same.

I think it is this ATT setting:
![grafik](https://github.com/zarillion/handynotes-plugins/assets/57680823/248a8553-9865-4cae-b360-fcb8c03d2a70)

**Comment by ghost** [comment]
Hello, thanks for your reply.
I tested the chat command, and YES i do have the "already known" in the tooltip. :)
![image](https://github.com/zarillion/handynotes-plugins/assets/122007087/e755d387-81b6-4f2e-aeab-89acc4ace0fb)


And yes i get it now about the monolith! It makes sense :) Thank you for that.
