### ISSUE TITLE
Miss use of unpack

### ISSUE THREAD

**Issue by Dairyman** [zarillion/handynotes-plugins#323]
The use of `unpack` here will only return one value not all values.
https://github.com/zarillion/handynotes-plugins/blob/79ece7fa820cb1c2bd12b83e7652e4352b6faeb0/plugins/10_Dragonflight/common.lua#L1439-L1466

See:
```Lua
print(unpack({1, 2, 3, 4}) -- prints: 1 2 3 4

print(1, unpack({2, 3, 4}), 5) -- prints: 1 2 5
```

**Comment by Dairyman** [comment]
https://github.com/zarillion/handynotes-plugins/blob/6dcfd20b2fa3ea533e7a4c77e4a86deba56bb4d0/plugins/10_Dragonflight/common.lua#L1487-L1501

There is one more.

**Comment by Krovikan** [comment]
One of our coders says that is not a problem the line 1500 because is the last thing in the table.
