### ISSUE TITLE
Dependency missing?

### ISSUE THREAD

**Issue by teetrixx** [zarillion/handynotes-plugins#324]
**ADDON VERSION**: (place version of the addon you have installed here)
V35 from March 26

**Describe the bug**
doesn't load in game due to ''dependency missing''

**Screenshots**
see screenshot below
![WoW addon issue](https://user-images.githubusercontent.com/131698719/234062498-46400d0f-be47-4cfd-ba0f-445daba6b913.PNG)

**Comment by Lightuky** [comment]
Do you have the base Handynotes addon installed ?

**Comment by teetrixx** [comment]
I don't know i thought that the most recent one was the base+update..

**Comment by Lightuky** [comment]
When you see addons named as such : "Handynotes : XXX", those are plugins that add to the base Handynotes addon.
In this case, the Dragonflight plugin needs the base addon to work.

**Comment by Krovikan** [comment]
I don't see more comments in a week and none have this issue. Is not a bug. I close the ticket. If needed, open again.

Regards
