### ISSUE TITLE
"Hide rare if all rewards known" not fully working first load

### ISSUE THREAD

**Issue by BradCOnGitHub** [zarillion/handynotes-plugins#325]
To reproduce I have to log out/in. Reloading does not work,

For some rares I have all of the items but opening the map will display them anyway. I -think- it only happens for maps that are not my current map. Closing and reopening the map makes the rare disappear (or turn white if the setting is off) as expected.

**Comment by Ioney** [comment]
can you post some screenshots of your settings and when hovering the rare on the map?
is it only on one rare or multiple?

**Comment by BradCOnGitHub** [comment]
> can you post some screenshots of your settings and when hovering the rare on the map? is it only on one rare or multiple?

It's every rare. Servers just went down but I can get you a screenshot later today.

The rares on the 14 hour cycle are the ones I'm primarily looking at, but it happens for all of them. I'll see every item in the tooltip as green/known but the icon is still present and/or blue. Simply toggling the map and navigating back to that zone will make it disappear/turn white.

**Comment by BradCOnGitHub** [comment]
options
![image](https://user-images.githubusercontent.com/15109073/235791603-3809d67a-6605-42dd-b857-a48faa9ba1b6.png)
first view
![image](https://user-images.githubusercontent.com/15109073/235791540-fb7624d5-a420-42b8-aacb-70f577e46ee0.png)
second view
![image](https://user-images.githubusercontent.com/15109073/235791678-eb5cb605-dcbb-4a60-96f0-f93712e1c623.png)

**Comment by Ioney** [comment]
i cant replicate this on my client.

@zarillion told me that this is a rare problem but we do not know exactly how it occurs
