### ISSUE TITLE
10.1.0 Usage: EJ_GetTierInfo(index) Invalid index 10

### ISSUE THREAD

**Issue by voidzone** [zarillion/handynotes-plugins#326]
**ADDON VERSION**: (place version of the addon you have installed here)
v35

**Describe the bug**
```
HandyNotes_Dragonflight/core/core.lua:197: Usage: EJ_GetTierInfo(index) Invalid index 10
[string "=[C]"]: in function `EJ_GetTierInfo'
[string "@HandyNotes_Dragonflight/core/core.lua"]:197: in function <HandyNotes_Dragonflight/core/core.lua:176>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
(*temporary) = 10
```

Appears to be a race condition issue because if I `/dump EJ_GetTierInfo(10)` in-game it doesn't throw any errors.

**Comment by Krovikan** [comment]
You are in the PTR of 10.1.0?

v35 don't work with PTR of 10.1.0. Is designed for 10.0.7.

Regards

**Comment by voidzone** [comment]
10.1 is live in NA.

**Comment by Krovikan** [comment]
In this case, soon will be a v36 for 10.1.0.

I close this. When v36 with support for 10.1.0 goes out, if you have this error you can open a new ticket.

Regards
