### ISSUE TITLE
Affects all your handynote addons.

### ISSUE THREAD

**Issue by dfurray** [zarillion/handynotes-plugins#328]
**ADDON VERSION**:  v35

**Describe the bug**
Seems like a simple lua error 

    -- Query localized expansion title
    if not ns.expansion then error('Expansion not set: ' .. ADDON_NAME) end
    local expansion_name = EJ_GetTierInfo(ns.expansion)
    ns.plugin_name = 'HandyNotes: ' .. expansion_name
    ns.options.name = ('%02d - '):format(ns.expansion) .. expansion_name
end

Looks like this got changed in the latest update.

**Comment by zarillion** [comment]
Already fixed, please download the newest versions.
