### ISSUE TITLE
Vignette Tooltips (CurseForge)

### ISSUE THREAD

**Issue by Ioney** [zarillion/handynotes-plugins#329]
> Is it possible to have the tooltips on rare icons show when hovering over the blizzard vignette? I think Rarescanner does it but I like using this addon for checking what I'm missing from a rare and one of the most important times to see that is when a rare spawns but the Handynotes icon just gets buried behind the blizzard vignette.

**Comment by zarillion** [comment]
I think if we start populating `vignette=id` fields on rare nodes, we can probably bake this functionality into the `Rare` node class.

**Comment by ghost** [comment]
That would be fantastic!
Unfortunately addons like SilverDragon dont support them. It would be very useful indeed.
