### ISSUE TITLE
Zaralek Cavern profession treasure reappears after learning

### ISSUE THREAD

**Issue by hollo6** [zarillion/handynotes-plugins#330]
**ADDON VERSION**: (place version of the addon you have installed here)
v36

**Describe the bug**
After looting a profession treasure item (Marrow-Ripened Slime), it correctly gets hidden from the map.
But upon learning (using) said item, it reappears on the map again.

**Comment by Ioney** [comment]
thanks for the report.
This happens because the hidden quest id is missing in our dataset.
We will fix it in our next release if we can get the id.

**Comment by Dathwada** [comment]
Added Marrow-Ripened Slime questID in e626556beaeb340105a1e1a199220e3fc9ba309c

Still missing questIDs for
- [x] Intricate Zaqali Runes (Inscription)
- [x] Hissing Rune Draft (Inscription)
- [x] Ancient Research (Inscription)
- [x] Snubbed Snail Shells (Jewelcrafting)
- [x] Defective Survival Pack (Engineering)
- [x] Inconspicuous Data Miner (Engineering)

**Comment by teelolws** [comment]
>  Defective Survival Pack (Engineering)

I don't think this is actually obtainable. At the spot on the map was Inconspicuous Data Miner instead. Or maybe its a Goblin vs Gnomish engineering thing?

**Comment by Dathwada** [comment]
@adavak added missing ids in 8650c113
