### ISSUE TITLE
"siege on dragonbane keep" appears to do nothing in Waking Shores

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#332]
Hello,

I keep toggling this on and off and dont see anything pop up on the map.
Checking "show completed" also has no effect.
Am I missing something or is this a bug?
Thanks :)

![image](https://user-images.githubusercontent.com/122007087/235972044-5a0638c7-a4c7-4dfe-9392-d17a6d90f7a6.png)

**Comment by ghost** [comment]
Update: I found what it does! It adds tooltip function over the siege blizz icon when it appears.
Problem is it only appears when a siege is active!
Is it possible to perhaps add a dedicated siege icon that will display this info all the time?
Similar to storm icons :)
Thanks

**Comment by Ioney** [comment]
Looks like the icon will only be rendered on the map if the siege is not active

https://github.com/zarillion/handynotes-plugins/blob/79f7349c716a1a70f94a2dc298621d29a0f5a0ad/plugins/10_Dragonflight/zones/waking_shores.lua#L2284-L2320

**Comment by ghost** [comment]
> Looks like the icon will only be rendered on the map if the siege is not active
> 
> https://github.com/zarillion/handynotes-plugins/blob/79f7349c716a1a70f94a2dc298621d29a0f5a0ad/plugins/10_Dragonflight/zones/waking_shores.lua#L2284-L2320

Hi, not sure what you mean to be honest!
Here is a screenshot for context in case it helps someone - as you can see siege is checked, siege is NOT active, and I dont see any icon the map :)
This screenshot was taken when siege timer is 30m left until it starts.

![image](https://user-images.githubusercontent.com/122007087/236572221-0cc3203c-bdf3-49dd-b655-117b14254144.png)
