### ISSUE TITLE
inscription knowledge "ancient research" wrong location

### ISSUE THREAD

**Issue by Fleymour** [zarillion/handynotes-plugins#334]
The HandyNotes location for this item near Loamm is incorrect.
There's a cavern in the north in the Aberrus Approach area which a rare spawns (Professor Gastrinax), the same cavern where the daily is to suck up the oozes;
entrance to the cavern is at 52.78, 18.85.

Enter the cavern, go through the first entrance hallway/lobby and turn right; you'll see a pair of undisturbed tables, a pair of disturbed tables, a large circular red rug/carpet, some oozes and some bookshelves.
Near the huge pile of black debris, one of the disturbed tables has a submerged corner; the item is under this table at 54.47, 20.26.
If you stand on top of it the prompt should pop up to collect the item --you can use the interact key if you have it bound.

i copied from : https://www.wowhead.com/item=206035/ancient-research#comments:id=5600304

**Comment by Ioney** [comment]
i already changed that in commit https://github.com/zarillion/handynotes-plugins/commit/e63d9e3ce93af542e85a1b0e664fbe02cc2339e8 and will be included in the next release version
