### ISSUE TITLE
Defective Survival Pack eng prof treasure marked in wrong spot

### ISSUE THREAD

**Issue by wheatbread** [zarillion/handynotes-plugins#336]
**ADDON VERSION**: (place version of the addon you have installed here)

**Describe the bug**
Defective Survival Pack engineering profession treasure in Zaralek Cavern is marked in the wrong spot.   Currently it is at 49.5, 58.8.  It should be at 50.50, 47.90.  I think it is interchanged with Inconspicuous Data Miner.

**Screenshots**

**Comment by Dathwada** [comment]
Thanks for the report.
@Ioney changed the location in 5210e254
