### ISSUE TITLE
Fealty's Reward isn't actually bugged

### ISSUE THREAD

**Issue by Wanny** [zarillion/handynotes-plugins#341]
From the comments on Wowhead:

"There is a nearby statue of a dragon (presumably a young Neltharion?) at 43.57, 23.02. Stand in front of this statue and /kneel. The statue which is normally inanimate will have its eyes light up and breathe fire. At this point, the Fealty's Reward chest becomes lootable!"

I just did that and indeed works. The chest gave me Crest Fragments, Flightstones, Dragon Isles Supplies..... and a trinket: Drakeforged Magma Charm.

As additional info:
- you have to /kneel while **not** riding a mount. I did that first and saw the action text but there was no reaction from the statue.
- on the wowhead comments they say that if you take too long to go back to the chest it can't be clicked on. Make sure to go back quickly.

**Comment by Dathwada** [comment]
Already changed in commit e626556.
This will be included in the next release.
