### ISSUE TITLE
Lua error with KR server : ZaralekRotation

### ISSUE THREAD

**Issue by Black-Beer** [zarillion/handynotes-plugins#342]
**ADDON VERSION**: v37 (KR server)
KR server

**Describe the bug**
Addon isn't working and they got a error from the Bugsack.

**Screenshots**
HandyNotes_Dragonflight/core/util.lua:291: attempt to perform arithmetic on field '?' (a nil value)
[string "@HandyNotes_Dragonflight/core/util.lua"]:291: in function `Initialize'
[string "@HandyNotes_Dragonflight/core/class.lua"]:56: in function `ZaralekRotation'
[string "@HandyNotes_Dragonflight/zones/zaralek_cavern.lua"]:69: in main chunk

Locals:
self = <table> {
 __address = "00000223869A81E0"
 id = 2
 __class = <table> {
 }
}
attrs = <table> {
 id = 2
}
region_initial = <table> {
 1 = 1683298800
 3 = 1683259200
}
(*temporary) = 172800
(*temporary) = nil
(*temporary) = 2
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field '?' (a nil value)"
-------------------------------------------
HandyNotes_Dragonflight/zones/azure_span.lua:1 (null)
HandyNotes_Dragonflight/zones/ohnahran_plains.lua:1 (null)
HandyNotes_Dragonflight/zones/thaldraszus.lua:1 (null)
HandyNotes_Dragonflight/zones/waking_shores.lua:1 (null)
HandyNotes_Dragonflight/zones/zaralek_cavern.lua:1 (null)
Interface\FrameXML\Bindings.xml:1 HandyNotes_Dragonflight/zones/azure_span.lua:1 (null)
Interface\FrameXML\Bindings.xml:1 HandyNotes_Dragonflight/zones/ohnahran_plains.lua:1 (null)
Interface\FrameXML\Bindings.xml:1 HandyNotes_Dragonflight/zones/thaldraszus.lua:1 (null)
Interface\FrameXML\Bindings.xml:1 HandyNotes_Dragonflight/zones/waking_shores.lua:1 (null)
Interface\FrameXML\Bindings.xml:1 HandyNotes_Dragonflight/zones/zaralek_cavern.lua:1 (null)

**Comment by adavak** [comment]
https://github.com/zarillion/handynotes-plugins/blob/3d446041abee7be3470b9f66cc1241aa36a9a9a7/core/util.lua

replace this file in `core` folder and `/reload` UI.

should be no error and wait for next release.

**Comment by pinkufairy** [comment]
It appears that some of the files are missing time data for the Korean server, which is causing the error. You need to modify the lua files in the HandyNotes_Dragonflight\zones folder.

For example, adding time information for the Korean server to the zaralek_cavern.lua file seems to work.

```
local ZaralekRotation = Class('ZaralekRotation', ns.Interval, {
    initial = {eu = 1683259200, us = 1683298800, kr = 1683759600, tw = 1683759600},
    offset = 86400,
    interval = 86400
})
```

**Comment by Black-Beer** [comment]
Bug fixed. thank you :)
