### ISSUE TITLE
Add this boat in Azure Span? 

### ISSUE THREAD

**Issue by Protuhj** [zarillion/handynotes-plugins#347]
https://old.reddit.com/r/wow/comments/13nxubg/this_boat_teleports_you_to_iskaara/

Maybe showing a line that it teleports you to Iskaara if moused-over?

**Comment by ghost** [comment]
Wow what a find! Yes yes please add this :)
So useful!!

**Comment by Ioney** [comment]
![grafik](https://github.com/zarillion/handynotes-plugins/assets/4973036/89c0cb2b-e96d-43d1-88a4-21ed76535495)

**Comment by Protuhj** [comment]
That looks great @Ioney!
