### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by purplemooni** [zarillion/handynotes-plugins#348]
1x HandyNotes_Dragonflight/core/util.lua:314: attempt to index upvalue 'L' (a nil value)
[string "@HandyNotes_Dragonflight/core/util.lua"]:314: in function `GetText'
[string "@HandyNotes_Dragonflight/core/nodes.lua"]:318: in function `Render'
[string "@HandyNotes_Dragonflight/core/core.lua"]:141: in function <HandyNotes_Dragonflight/core/core.lua:140>

Locals:
self = <table> {
 __address = "0x7fa743f802f0"
 SpawnTime = 1677366000
 id = 17
 __class = <table> {
 }
}
TimeFormat = "%B %d - %H:%M local time"
NextSpawn = 1684976400
TimeLeft = 34
(*temporary) = nil
(*temporary) = 1677366000
(*temporary) = 1684976400
(*temporary) = 34
(*temporary) = 1684976400
(*temporary) = 34
(*temporary) = 50400
(*temporary) = "attempt to index upvalue 'L' (a nil value)"
ns = <table> {
 GetIconLink = <function> defined @HandyNotes_Dragonflight/core/icons.lua:108
 GROUP_HIDDEN75 = <table> {
 }
 NameResolver = <table> {
 }
 DRAGON_CUSTOMIZATIONS = <table> {
 }
 color = <table> {
 }
 WorldMapDataProvider = <table> {
 }
 requirement = <table> {
 }
 SetOpt = <function> defined @HandyNotes_Dragonflight/core/options.lua:63
 status = <table> {
 }
 COLORS = <table> {
 }
 Group = <table> {
 }
 tomtom = <table> {
 }
 group_types = <table> {
 }
 maps = <table> {
 }
 world_map_button = Krowi_WorldMapButtons1 {
 }
 IsInstance = <function> defined @HandyNotes_Dragonflight/core/class.lua:86
 faction = "Alliance"
 icons = <table> {
 }
 class = "DRUID"
 Intervals = <table> {
 }
 expansion = 10
 BootstrapDevelopmentEnvironment = <function> defined @HandyNotes_Dragonflight/core/dev.lua:30
 groups = <table> {
 }
 professions = <table> {
 }
 node = <table> {
 }
 Error = <function> defined @HandyNotes_Dragonflight/core/dev.lua:285
 reward = <table> {
 }
 optionDefaults = <table> {
 }
 options = <table> {
 }
 GetColorOpt = <function> defined @HandyNotes_Dragonflight/core/options.lua:68
 Warn = <function> defined @HandyNotes_Dragonflight/core/dev.lua:280
 GROUP_HIDDEN = <table> {
 }
 Class = <function> defined @HandyNotes_Dragonflight/core/class.lua:10
 PlayerHasProfession = <function> defined @HandyNotes_Dragonflight/core/util.lua:173
 plugin_name = "HandyNotes: Dragonflight"
 locale = <table> {
 }
 MinimapDataProvider = HandyNotes_DragonflightMinimapDP {
 }
 Map = <table> {
 }
 CreateGlobalGroupOptions = <function> defined @HandyNotes_Dragonflight/core/options.lua:338
 Interval = <table> {
 }
 GetIconPath = <function> defined @HandyNotes_Dragonflight/core/icons.lua:102
 AsTable = <function> defined @HandyNotes_Dragonflight/core/util.lua:230
 GetGlowPath = <function> defined @HandyNotes_Dragonflight/core/icons.lua:117
 RenderLinks = <function> defined @HandyNotes_Dragonflight/core/util.lua:73
 poi = <table> {
 }
 HEXtoRGBA = <function> defined @HandyNotes_Dragonflight/core/util.lua:253
 Debug = <function> defined @HandyNotes_Dragonflight/core/dev.lua:275
 addon = <table> {
 }
 GROUP_ALPHA75 = <table> {
 }
 GetOpt = <function> defined @HandyNotes_Dragonflight/core/options.lua:62
 AsIDTable = <function> defined @HandyNotes_Dragonflight/core/util.lua:238
 PrepareLinks = <function> defined @HandyNotes_Dragonflight/core/util.lua:57
 CreateGroupOptions = <function> defined @HandyNotes_Dragonflight/core/options.lua:382
 IsClass = <function> defined @HandyNotes_Dragonflight/core/class.lua:82
 NewLocale = <function> defined @HandyNotes_Dragonflight/core/util.lua:211
 Clone = <function> defined @HandyNotes_Dragonflight/core/class.lua:96
 PlayerHasItem = <function> defined @HandyNotes_Dragonflight/core/util.lua:169
 SetColorOpt = <function> defined @HandyNotes_Dragonflight/core/options.lua:73
 GetDatabaseTable = <function> defined @HandyNotes_Dragonflight/core/util.lua:185
}
L = nil

**Comment by Ioney** [comment]
what client language do you use?
