### ISSUE TITLE
Hovering Elemental Storm while in another zone shows the wrong info

### ISSUE THREAD

**Issue by Onyxx666** [zarillion/handynotes-plugins#349]
**ADDON VERSION**: (v38 on 10.1.0)

**Describe the bug**
So if you select Thaldraszus and you can see an Elemental Storm up in a different zone say like The Waking Shores it will show the hover stats for the zone you have selected instead of the location the storm is currently in.

**Screenshots**
https://imgur.com/a/pMiUEkN

**Comment by Ioney** [comment]
there is no information from the game in which region the storm is happening.
you can only differentiate the storm type by the POI ID but not the region it spawned in.

**Comment by Onyxx666** [comment]
> 

Figured as much just wanted to check. Thanks!
