### ISSUE TITLE
Low FPS in certain situations with HandyNotes Shadowlands

### ISSUE THREAD

**Issue by 7MinutesDead-Git** [zarillion/handynotes-plugins#35]
While minimap rotation is enabled, if you highlight a rare boss icon in Icecrown to show the spawn rotation path, then whenever you turn your character and the minimap rotates, your framerate will drop tremendously.

It's a bit strange to describe so I recorded some footage of it. Watch the FPS counter in the top left to see effects:
https://streamable.com/6ic1kx

I'm not sure if it's an interaction with ElvUI or if it does this by default, but either way it can be resolved by just disabling minimap rotation. But I thought I'd submit the issue.

**Comment by Krovikan** [comment]
ElvUI_Klix was a problem related with https://github.com/zarillion/handynotes-plugins/issues/27

The FPS drops is related with the MBB addon in this link https://github.com/zarillion/handynotes-plugins/issues/29

Now the question is, you have installed the MBB addon?


Regards

**Comment by 7MinutesDead-Git** [comment]
> Now the question is, you have installed the MBB addon?  
  
I have not. My enabled addons are as follows:  
![Wow 2020-11-15 10-31-23](https://user-images.githubusercontent.com/50963144/99189236-d96cee00-2725-11eb-8395-2161ac5e5d9c.png)

**Comment by Krovikan** [comment]
What version of HandyNotes and what from HandyNotes: Shadowlands are you using?

Regards

**Comment by 7MinutesDead-Git** [comment]
> What version of HandyNotes and what from HandyNotes: Shadowlands are you using?  
  
HandyNotes shows 1.6.0, and HandyNotes Shadowlands shows v17.  
  
Here's the settings:  
![image](https://user-images.githubusercontent.com/50963144/99190644-4637b680-272d-11eb-86f0-980ae8726d00.png)
![image](https://user-images.githubusercontent.com/50963144/99190652-564f9600-272d-11eb-8621-6b8c22a4e1e1.png)

**Comment by zarillion** [comment]
There's definitely a lot of POIs to redraw there. I have added a new option to change the refresh rate of minimap POIs when 'Rotate Minimap' is enabled.

![image](https://user-images.githubusercontent.com/64381982/99195380-e5b77200-274a-11eb-91f5-8de3cf6a12bc.png)

I determined empirically that a default value of `0.05` appears the alleviate the stress on FPS when redrawing many POIs at once without causing the rotation of the textures to get too out of sync with player facing before the next refresh. The slider allows you to increase this value further if the rotational jitter it causes does not bother you.

This was just released in v18.

**Comment by zarillion** [comment]
I pondered this some more and found a different solution that updates the POI texture rotations fast enough to do it on every update to player facing again. I've removed the above option for v19, which I will release some time soon. For now, the temporary option in v18 will help.

**Comment by 7MinutesDead-Git** [comment]
Hell yeah nice job man. Thanks for looking at this.
