### ISSUE TITLE
Wrong quest ID for Underlight Queen

### ISSUE THREAD

**Issue by Protuhj** [zarillion/handynotes-plugins#351]
**ADDON VERSION**: Dragonflight v38

**Describe the bug**
After you kill the Underlight Queen, her icon doesn't disappear. Checking the zaralek_cavern.lua file, it looks like it's using quest ID `75297`, but it seems like the quest should be `75298`: https://www.wowhead.com/quest=75298/underlight-queen

**Comment by Dathwada** [comment]
The questID `75297` is correct, but somehow the questID changes back to false after a few seconds.
![grafik](https://github.com/zarillion/handynotes-plugins/assets/57680823/e830bb4f-f57e-43f4-b64e-83728dd5968f)

https://wago.tools/db2/Vignette?filter[Name_lang]=%09Underlight%20Queen&page=1&build=10.1.0.49801

**Comment by Protuhj** [comment]
Interesting. Must be a WoW bug then?

**Comment by Dathwada** [comment]
I think so, at least I reported it ingame as a bug. Let's see if they'll fix it if it is their mistake.

**Comment by Protuhj** [comment]
Going to close as it's likely a wow issue, not a plugin one.
