### ISSUE TITLE
[Dragonflight]: Invoq missing loot: Molten Lava Pack

### ISSUE THREAD

**Issue by Protuhj** [zarillion/handynotes-plugins#353]
https://www.wowhead.com/item=205796/molten-lava-pack

**Comment by Krovikan** [comment]
Hello:

In comments, Blizzard says:

```
Thanks a lot for getting in touch with us about this, I am really sorry to hear luck hasn’t been favourable to you recently, but such is the nature of the game when it comes to drops and loot. I absolutely understand the frustration though!

The ingame systems have been designed to drop loot randomly, based on a number of factors of chance. In short, this basically means there is never a guarantee of any particular item dropping, even after many attempts.

Take heart however, as the law of averages does mean eventually it will be gained, and this truly is a case of persistence pays off! I encourage that you keep trying and I am sure you'll get better items to drop for you.
```

For Blizzard is all OK. I remember a pet of a parrot that drops in The Cape of Stranglethorn with a drop of 0,0006% and was normal.

Also for the mount of a rocket, the X-45 Heartbreaker, from the Alchemists in the "Love is in Air" event.

Sorry, but we can't do nothing if for Blizzard is normal.

Regards

**Comment by Protuhj** [comment]
What? Are you a bot?

**Comment by Protuhj** [comment]
What does that quote have to do with anything?

The rare is supposed to drop that toy but the plugin doesn't have it? Do you not add super low drop rate items to the plugin?

**Comment by zarillion** [comment]
It looks like this reward has been added but not released. I'm going to put out a new release today.

**Comment by Krovikan** [comment]
> What does that quote have to do with anything?

The only thing if you don't add information of what are you requesting. With only a link I can't know what are you asking.

Regards

**Comment by Protuhj** [comment]
The title says what the link is for.
