### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Milky063** [zarillion/handynotes-plugins#355]
**ADDON VERSION**: (HandyNotes_Dragonflight-v40.zip)

**Describe the bug**
A clear and concise description of what the bug is and how to reproduce it.

6x [ADDON_ACTION_BLOCKED] AddOn 'HandyNotes' tried to call the protected function 'Frame:SetPassThroughButtons()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetPassThroughButtons'
[string "@HandyNotes/HandyNotes.lua"]:371: in function `OnAcquired'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:201: in function `AcquirePin'
[string "@HandyNotes/HandyNotes.lua"]:347: in function `RefreshPlugin'
[string "@HandyNotes/HandyNotes.lua"]:416: in function `UpdateWorldMapPlugin'
[string "@HandyNotes/HandyNotes.lua"]:503: in function `?'
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@HandyNotes_Dragonflight/core/core.lua"]:284: in function `RefreshImmediate'
[string "@HandyNotes_Dragonflight/core/core.lua"]:279: in function <HandyNotes_Dragonflight/core/core.lua:277>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Screenshots**

none

**Comment by Dairyman** [comment]
Add to `core/map.lua` after `WorldMapPinMixin` creation
```Lua
function WorldMapPinMixin:SetPassThroughButtons() end
```

See https://github.com/Stanzilla/WoWUIBugs/issues/453
