### ISSUE TITLE
Infinitely duplicating and expanding tooltip with Rarescanner

### ISSUE THREAD

**Issue by Starfighter7201** [zarillion/handynotes-plugins#357]
**ADDON VERSION**: 40

**Describe the bug**
When both Rarescanner and this handynotes plugin are enabled, the tooltip of this plugin duplicates infinitely until it fills the entire screen. 

**Screenshots**

![Screenshot 2023-07-22 172906](https://github.com/zarillion/handynotes-plugins/assets/64983999/ff3c8785-f91a-4401-8d33-2aa328160c63)

**Comment by Ioney** [comment]
Looks like RareScanner somehow messes with the Blizz Tooltip for Vignettes and maybe replaces it with its own tooltip frame (not 100% sure about that).

A quick fix would be to not show the rewards when RareScanner is loaded. The Tooltips overlap anyway and RareScanner basically has the same information as we do (achievements and transmog).

**Comment by ghost** [comment]
I believe this will be fixed in the next release
