### ISSUE TITLE
4 missing or wrong data

### ISSUE THREAD

**Issue by pepedressingroom** [zarillion/handynotes-plugins#369]
HandyNotes_Dragonflight
Version: 42

**thaldraszus.lua**

1. -- Zal'kir the Chosen (npc:205865) missing daily quest id: 76170, 77335 (76170 is used by addon "All the things",  77335 not sure)

2. --There are TWO Forgetful Apprentice's Tome {item:198659}(Inscription Treasures), and nodes[47104007] is the missing one.

LOOT quest id: 70248
--desc: Above Algeth'era FP, just west in a small building. Click the Curious Glyph (book){object:380570} to get the buff Making Connections{spell:384818}.
Leave the building and go to the other side of the bridge. At the end you will find Confusion Manifest{npc:194880}. Kill it and loot  Decryption Key{item:198672}. Go back to the Curious Glyph (book){object:380584} and click it again to loot Forgetful Apprentice's Tome{item:198659}. 
/way 47.10 40.07 Curious Glyph (book)
/way 49.84 40.31 Confusion Manifest
ref:
https://www.wowhead.com/guide/professions/knowledge-point-treasure-locations-dragon-isles
https://www.wowhead.com/item=198659/forgetful-apprentices-tome#comments
--desc local: Curious Glyph, 奇特的雕文--zhCN

**zaralek_cavern.lua**

1. --CuriousTopHat missing 3 more nodes, which list on the wowhead comment page and I have confirmed of them.
/way #2133 61.73 69.79 
/way #2133 63.20 55.74 
/way #2184 70.01 65.55 --in the cave, (out of cave 2133:63963763)
ref:
https://www.wowhead.com/npc=205010/curious-top-hat#comments

2. --Stolen Stash, nodes[60664622] has 2 quest ids. 66382 is wrong, and it's a weekly loot quest of Blacksmithing knowledge point item from chests source. please remove 66382.

**Comment by Ioney** [comment]
thanks for letting us know.

while working on the fixes in zaralek i noticed that the Crystal-Encased Chest wasnt disappearing, do you have any information about the quests that get triggered from that treasure?

**Comment by pepedressingroom** [comment]
```
map.nodes[36397425] = Treasure({
    note = L['crystal_encased_chest_note'],
    quest = {74987, 75559, 75601, 73697, 74986},
```
74987--blue
75559--red
75601--animation
74986--loot
please remove ", 73697", it's the loot quest of Ancient Zaqali Chest

ref: https://raw.githubusercontent.com/DFortun81/AllTheThings/master/db/Dragonflight/Categories.lua
`n(-1000036,{i(205260,{b=1}),o(386104,{coords={{36.7,48.8,2133}},description="Interact with Bottled Magma at 36.5 48.2",questID=73697,g={crit(59222,{achID=17786,awp=30001})}})`
