### ISSUE TITLE
Add Option to just never hide dragon races

### ISSUE THREAD

**Issue by MysticalOS** [zarillion/handynotes-plugins#374]
even if all completed.

As it stands now,  basically have to disable "show completed" but then manually hide a few dozen nodes, just so I could work on challenge races.

Adding support for challenge races also would be nice but then when they add "mega ultra challenge" or whatever damn mode they add next, same problem. can't find them without unhiding complete or waiting for an update. I think it'd just be cleaner to just have an option to "always show races"

**Comment by kyletmartinez** [comment]
All challenge races have been added just not released yet. But you bring up a good point about making the nodes readily available. We can discuss as a team and figure out a solution!

**Comment by Dathwada** [comment]
Hi, all challenge and reverse challenge races are already added but a new version with them was not released yet.

One solution for the "always show races" could look like this:
![](http://puu.sh/JTxhU/4bdd5ec092.jpg)

**Comment by zarillion** [comment]
Hey @MysticalOS! I added a comment to Dath's PR here: https://github.com/zarillion/handynotes-plugins/pull/375#issuecomment-1894796778

> I'm going to close this one for now. Lets wait and see what they do with these races in the future. When they add new races next expansion, will they trickle out the race types like they did this expansion or will we get forward, reverse, advanced, etc all at once?
>
> This feature was requested because they trickled them out this time. People wanted to turn the race icons back on before we had released the update with the new race rewards. If they all come out at once next expansion, then this feature wouldn't be necessary. We would have all the data from the start and never update that node again.
>
>If we need it we can come back, reopen and merge this PR.

I'd like to wait and see how the race types are rolled out in War Within before we add this option.

**Comment by Dathwada** [comment]
Blizzard is adding this option with 10.2.7
> The location of Dragonriding Races can now be toggled in the Map filter.

[Source](https://www.wowhead.com/news/patch-10-2-7-dark-heart-development-notes-mythic-lfg-improvements-338643)
