### ISSUE TITLE
The 'Phoenix Wishwing' Ungoro Node Display Error

### ISSUE THREAD

**Issue by pepedressingroom** [zarillion/handynotes-plugins#380]
**ADDON VERSION**: (master)

**Describe the bug**
_waking_shores.lua_
Phoenix Wishwing `ungoro.nodes[50005000]` in Ungoro do not correctly displayed, while release version (Version: 42) works well.
When in Ungoro,  the menu button in the upper-right corner do not show drop down list when clicking on it.

**Screenshots**
![WoWScrnShot_110723_021542](https://github.com/zarillion/handynotes-plugins/assets/119722554/4b8efb57-89c4-4b36-96ce-e5e050f7bcd7)

**Comment by Dathwada** [comment]
I'm on master and I can't reproduce this. It works fine in Retail and PTRX in a german and english client for me.

**Comment by pepedressingroom** [comment]
@Dathwada It seems I had partially updated the core that caused this.
Sorry.
