### ISSUE TITLE
Dragonflight: Elianna and Talisa Whisperbloom (in ED) nodes overlap Central Encampment icon

### ISSUE THREAD

**Issue by Protuhj** [zarillion/handynotes-plugins#381]
**ADDON VERSION**: v43

**Describe the bug**
When trying to mouseover the Elianna or Talisa Whisperbloom icons, you have to be real precise to not mouse over the Cental Encampment icon instead.

**Comment by Ioney** [comment]
i'm not sure, but i don't think we can force the frame strata of the node icons. it's probably set by HandyNotes.

**Comment by zarillion** [comment]
It is possible, but not directly through the interface HandyNotes provides. You have to re-assign the strata manually for those specific nodes using hooks. There was an example in the prepatch for Dragonflight:

https://github.com/zarillion/handynotes-plugins/blob/0778b0a6cf68db63ef6f54e2ea97a95f7037b494/plugins/09_Shadowlands/zones/prepatch.lua#L150-L160

Basically you add a custom hook for all HandyNotes pins, find a way to filter down to the pins you want (in this case, we used the texture) and then modify those pins.

**Comment by Protuhj** [comment]
If the nodes were offset, or displayed otherwise, that would be sufficient.

If the strata can solve the problem too, that would be ideal of course.

**Comment by hollo6** [comment]
I came here to suggest moving Elianna's icon a bit further away from the center, that way it would also be more easily identifiable and more visible that there actually is an icon for the NPC.

**Comment by Protuhj** [comment]
~~This seems to be fixed in 44 -- @Ioney or @zarillion if you can confirm this was fixed, then the issue can be closed.~~

Edit: on second look, it seems like it just depends if I scale the icons up then it "appears" to be fixed, but then the icons overlap. Sorry for the ping.

**Comment by Protuhj** [comment]
I'm going to close this in favor of a different issue, because these nodes should probably be moved.
