### ISSUE TITLE
Add portal locations in Valdrakken?

### ISSUE THREAD

**Issue by Protuhj** [zarillion/handynotes-plugins#383]
There are multiple portal locations in Valdrakken, it might be useful to show an icon for the different ones?

**Comment by Ioney** [comment]
do you mean the seasonal portals? there are other addons from @Dathwada for that.

**Comment by Protuhj** [comment]
I was primarily thinking of the Everbloom portal (which has now been added in the latest revision), but thought the seasonal ones might be good to have as well.

I think the seasonal portal locations are perfectly within this addon's scope, considering how many things it currently tracks.

I'm going to close this since the Everbloom portal was added, though I think the others will be worth having too.
