### ISSUE TITLE
Options 'show_all_transmog_rewards' and 'hide_done_rares' do not work well together

### ISSUE THREAD

**Issue by MKoep** [zarillion/handynotes-plugins#384]
Rares are hidden when 'show_all_transmog_rewards' and 'hide_done_rares' are enabled even if there are unknown transmogs for other characters.

Is there an option to show these rares without enabling 'show_completed_nodes'?

**Comment by Dathwada** [comment]
If you have enabled '**Show unobtainable transmog rewards**' and '**Hide rare if all rewards known**' the rare is hidden because your current character is not capable of learning any more transmogs from this rare and will be considert as "**all rewards known**".

**Comment by MKoep** [comment]
Yes, but it would be nice to use the plugin in account mode to show rares that drop unknown transmog for my account and not only for the current character.

**Comment by Ioney** [comment]
most transmog is soulbound. you cant farm it with one char to get transmogs for another.

this feature would only be usefull in the next expansion where transmog is learned no matter which class dropped it

**Comment by MKoep** [comment]
You are right, but I farm rares with 4 accounts simultaneously. My main character is flying in full screen and the three other characters are following. I use handynotes on my main character to see whether there are rares with missing transmog for all accounts.

**Comment by Ioney** [comment]
After talking to @zarillion he decided that we will look into implementing that in the next expansion.

if you really need this feature now you can edit the code of the `Transmog:IsObtained()` or `:IsLearnable()` function in `core/rewards.lua` as a workaround. this might get you  what you want.

**Comment by MKoep** [comment]
Thank you ;-)

**Comment by M-Koeper** [comment]
Hi, this ist still an issue for me.

It would be nice to have an option that puts the plugin in account mode. 
This should return `true` in `Transmog:IsLearnable()` and `Transmog:IsObtainable()`
