### ISSUE TITLE
v44 shows incorrect rewards, reward types and completion (blue skull instead of white) for several rares in the Emerald Dream

### ISSUE THREAD

**Issue by hollo6** [zarillion/handynotes-plugins#385]
**ADDON VERSION**: v44

**Describe the bug**
Some rares in the Emerald Dream show incorrect rewards or reward types on their tooltips or icon completion state.
Didn't have time to take a screenshot of Mosa Umbramane, it was showing [Owlbear's Decisive Strike](https://www.wowhead.com/item=208375/owlbears-decisive-strike) being a Recipe on a Tailor/Enchanter character.
See screenshots for other issues I've found.

**Screenshots**
this item should be a Recipe and only shown for Scribes (my character is not one), and it doesn't drop from this rare:
![image](https://github.com/zarillion/handynotes-plugins/assets/365584/1eb79f36-1138-4fef-896b-deff2b5fd427)
still blue even though all rewards are known (works correctly in v43):
![image](https://github.com/zarillion/handynotes-plugins/assets/365584/87fcc329-b729-4ada-ae67-894dfcd72e62)

**Comment by hollo6** [comment]
Found two more, these already exist in v43:
![image](https://github.com/zarillion/handynotes-plugins/assets/365584/3787ec17-1fbb-4fb5-918c-54a836e7c059)
![image](https://github.com/zarillion/handynotes-plugins/assets/365584/c4e4ee12-496d-4864-9462-254a504c6d7e)

**Comment by Dathwada** [comment]
Which class do you play?
Are all screenshots from your Tailor/Enchanter character ?

**Comment by hollo6** [comment]
First 2 screenshots (Bloodstripe Great Ray, Splinterlimb) are from Druid (Herb/Alchemy), the others from Warlock (Tailor/Enchanter).
But I have every class and every profession I can test with if that helps.

**Comment by Dathwada** [comment]
Please try to disable and re-enable the rares and see if this fixes the rares are still blue for now.
![ss+(2023-11-11+at+06 32 20)](https://github.com/zarillion/handynotes-plugins/assets/57680823/3885294f-9657-48fd-9a92-be5081224c1c)

- Fixed Mosa Umbramane loot.
- [Bloodstripe Great Ray](https://www.wowhead.com/npc=210050/bloodstripe-great-ray#drops) drops no recipe (see wowhead)
    - I'll also remove Hairy Chin

Screenshots from my druid with alchemy and enchanting

**Comment by hollo6** [comment]
I just updated back to v44 to test if re-enabling the rares fixes this issue but it seems to work after login/reload. I have noticed this on both characters after some time of normal gameplay, so there must be some trigger for this behavior.

**Comment by hollo6** [comment]
Now the still blue problem happened after logging in and doing nothing special. Re-enabling rares fixed it but only temporarily.

**Comment by Dathwada** [comment]
It looks like only rares that have recipes as a reward are affected.

**Comment by Ioney** [comment]
@Dathwada can you try to add
```lua
function Recipe:IsObtainable() return ns.PlayerHasProfession(self.profession) end

```
to line 450 in core/rewards.lua

maybe this helps?

**Comment by hollo6** [comment]
> ```lua
> function Recipe:IsObtainable() return ns.PlayerHasProfession(self.profession) end
> ```
> 
> to line 450 in core/rewards.lua
> 
> maybe this helps?

I don't think that would help because the affected characters have that profession and learned those recipes.

**Comment by Dathwada** [comment]
> @Dathwada can you try to add
> 
> ```lua
> function Recipe:IsObtainable() return ns.PlayerHasProfession(self.profession) end
> ```
> 
> to line 450 in core/rewards.lua
> 
> maybe this helps?

Doesn't work.

The issue is that `Recipe:IsObtained()` returns false at login.

**Comment by Dathwada** [comment]
I checked this on the TWW beta and it looks like this is fixed and we can determine at login if a recipe is obtained.

**Comment by zarillion** [comment]
Closing as this hasn't had any activity in almost a year.
