### ISSUE TITLE
Frame Freezes when dragonflying

### ISSUE THREAD

**Issue by Zifijo** [zarillion/handynotes-plugins#386]
Hello all,
This latest bug is happening with the v44 update that released today on 11/11.

I noticed when dragon flying that the game will freeze for a split second, most notably after using either Ascent or Forward abilities.
I have disabled all addons and tested everything one by one and came up with this version of the update being the issue.
Installing the v43 version removes this problem.

LMK if you need more info :).

**Comment by Ioney** [comment]
Do you still have freezes?
My game runs smoothly unless i hover over an Emerald Bounty. this is because the game client redraws it about every second

**Comment by softlie** [comment]
I've noticed this issue as well and narrowed it down to HandyNotes: Dragonflight. It's not only while dragonriding, it makes my entire game stuttery when in the Emerald Dream. I can't really tell if it persists in other zones but if it does it's much less noticeable than in the dream.

**Comment by Brevvi90** [comment]
I am having exactly the same issue, causes severe freezing and FPS issues. I was dragonriding when I noticed it because I'm moving so fast, but also happens when not dragonriding. I disabled all Addons and used one at a time and it was definitely Handynotes doing it.

**Comment by zarillion** [comment]
Closing as this hasn't had any activity in almost a year.
