### ISSUE TITLE
Add Rare Talthonei Ashwhisper spawn location

### ISSUE THREAD

**Issue by Forestspirit** [zarillion/handynotes-plugins#391]
<img width="442" alt="Untitled" src="https://github.com/zarillion/handynotes-plugins/assets/5016751/19b2825a-40dc-4038-aecf-b12f0eb59fd9">

**Comment by Protuhj** [comment]
The icon for Talthonei should also state that it'll spawn after you kill enough mobs in the different spawn areas.

https://www.wowhead.com/npc=209902/talthonei-ashwhisper#comments

**Comment by Dathwada** [comment]
> The icon for Talthonei should also state that it'll spawn after you kill enough mobs in the different spawn areas.
> 
> https://www.wowhead.com/npc=209902/talthonei-ashwhisper#comments

was added in 1955bf0

**Comment by Dathwada** [comment]
I'm closing this now, due to the release of v45.
