### ISSUE TITLE
Bloodstripe Great Ray shows wrong loot item

### ISSUE THREAD

**Issue by Protuhj** [zarillion/handynotes-plugins#392]
The icon says it has [Winding Slitherdrake: Hairy Chin](https://www.wowhead.com/item=203311/winding-slitherdrake-hairy-chin) but that item is created from inscription and doesn't drop anywhere.

**Comment by Dathwada** [comment]
See Issue #385.

Was already changed.

**Comment by Protuhj** [comment]
Good call, closing!
