### ISSUE TITLE
Fruit of the Bloom (achievment, map icons)

### ISSUE THREAD

**Issue by Fleymour** [zarillion/handynotes-plugins#394]
hey it seems the Fruit of the Bloom is tracked as completed / hides the Dreamfruit spawn icons on the map even without completion. (im missing Nae'dra Nibbles). also the West Dreamfruit is NEVER shown on the map :(

helpful infos about where / what are these providing 
https://www.wowhead.com/achievement=19310/fruit-of-the-bloom#comments:id=5733174

**Comment by Dathwada** [comment]
Hi, I updated Fruit of the Bloom already in commit 8b43d7da.

This change will be included in the next release.

**pls don't close this issue, we will close it with the release of the new version.**

**Comment by Dathwada** [comment]
I'm closing this now, due to the release of v45.
