### ISSUE TITLE
Add POI for Verlann Timbercrush

### ISSUE THREAD

**Issue by jsutan** [zarillion/handynotes-plugins#395]
Add a POI for [Verlann Timbercrush](https://www.wowhead.com/npc=207554/verlann-timbercrush) with associated drops (Cosmetic and Drake Manuscripts). He is the final part of the Superbloom event and has unique drops.

Location should be Emerald Dream, 43.92, 72.65, or added to the existing Superbloom POI.

**Comment by pepedressingroom** [comment]
[Loot from Verlann Timbercrush](https://github.com/zarillion/handynotes-plugins/pull/387/commits/545839db655e647f54925b36cc1f9fbf934b4528)
