### ISSUE TITLE
Suggestion/Feature Request: Add "Already Killed" Indicators For NPCs In The 10.2 Druid Forms Checklist

### ISSUE THREAD

**Issue by jneuls** [zarillion/handynotes-plugins#396]
I suppose the title pretty well covers the ask.

- Could use color coding?
    - `if (isFormCollected) then npcNameColor = "ffffff"; end`
    - `if (not isLootable and not isFormCollected) then npcNameColor = "808080"; end`
    - `if (isLootable and not isFormCollected) then npcNameColor = "00ff00"; end`
- Strikethrough NPC names in the list that are no longer lootable? (Regardless of the Druid Form collection status.)

Thanks and keep up the great work!

**Comment by ghost** [comment]
@jneuls I added an additional node with a checklist for rare kills around The Emerald Dream. Rares with forms already collected will disappear from the list. Rares with a daily kill will mark as (Completed). I'm currently not sure how to check for boss kills in an instance.

![Screenshot 2024-01-17 121523](https://github.com/zarillion/handynotes-plugins/assets/88683851/93692c54-1a22-41e0-8454-093f3dfd205f)

**Comment by Dairyman** [comment]
@wyldclaw 
https://github.com/zarillion/handynotes-plugins/blob/601bbf2f4920d8251235531d53d9d12f1a247d5a/plugins/10_Dragonflight/zones/emerald_dream.lua#L1250
and 
https://github.com/zarillion/handynotes-plugins/blob/601bbf2f4920d8251235531d53d9d12f1a247d5a/plugins/10_Dragonflight/zones/emerald_dream.lua#L481
have the same coords.

**Comment by ghost** [comment]
@Dairyman Good catch! Thank you. I also fixed the node from automatically hiding on login too.
