### ISSUE TITLE
Error when clicking on the icon option in the upper right corner of the world map

### ISSUE THREAD

**Issue by tommy610** [zarillion/handynotes-plugins#400]
**ADDON VERSION**: (place version of the addon you have installed here)
v46

**Describe the bug**
Error pops up when trying to click the options in the upper right corner of the world map. No options pop up, not sure if it's your handy note plugin is causing it or the actual handynote addon is causing it.

10x ...akAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1321: attempt to index field 'NewFeature' (a nil value)
[string "@WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1321: in function `UIDropDownMenu_AddButton'
[string "@HandyNotes_Dragonflight/core/templates.lua"]:115: in function `AddGroupButton'
[string "@HandyNotes_Dragonflight/core/templates.lua"]:187: in function `InitializeDropDown'
[string "@HandyNotes_Dragonflight/core/templates.lua"]:46: in function `initFunction'
[string "@WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:771: in function `UIDropDownMenu_Initialize'
[string "@WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1781: in function `ToggleDropDownMenu'
[string "@HandyNotes_Dragonflight/core/templates.lua"]:63: in function <...ceHandyNotes_Dragonflight/core/templates.lua:59>

Locals:
self = <table> {
 UIDropDownMenu_SetButtonText = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2085
 containsMouse = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1920
 UIDropDownMenu_DisableButton = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2069
 Create_UIDropDownCustomMenuEntry = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2293
 UIDropDownMenu_Refresh = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1448
 UIDropDownMenu_Initialize = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:762
 UIDropDownMenu_SetSelectedName = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1568
 UIDropDownMenu_SetDropDownEnabled = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2111
 UIDropDownMenu_SetInitializeFunction = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:789
 UIDropDownMenu_GetSelectedID = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1594
 UIDropDownMenu_MatchTextWidth = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1953
 DropDownExpandArrowMixin = <table> {
 }
 UIDropDownMenuButton_ShouldShowIconTooltip = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:118
 UIDropDownMenu_InitializeHelper = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:92
 DropDownMenuButtonMixin = <table> {
 }
 UIDropDownMenuButton_GetName = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2055
 UIDropDownMenu_ClearAll = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2000
 UIDropDownMenu_GetCurrentDropDown = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2043
 UIDropDownMenu_JustifyText = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2019
 UIDropDownMenu_IsEnabled = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2160
 UIDropDownMenu_RefreshDropDownSize = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:820
 UIDropDownMenu_EnableButton = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2073
 UIDropDownMenu_SetFrameStrata = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:816
 UIDropDownMenu_AddButton = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:985
 UIDropDownMenu_GetButtonWidth = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1400
 CloseDropDownMenus = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1881
 UIDropDownMenu_HandleGlobalMouseEvent = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1925
 ColorPicker_GetPreviousValues = <function> defined @AngryKeystones/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2158
 Create_UIDropDownMenu = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:748
 UIDropDownMenu_SetButtonWidth = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1980
 UIDropDownCustomMenuEntryMixin = <table> {
 }
 UIDropDownMenuButton_OpenColorPicker = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2059
 UIDropDownMenu_AddSeparator = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:943
 UIDropDownMenuButton_GetChecked = <function> defined @We

**Screenshots**

**Comment by Krovikan** [comment]
Hello @tommy610 :

I can see a lot of errors about Weak Auras. Try to disable Weak Auras only.

If your problem persists, try to disable HandyNotes: Dragonflight and enable Weak Auras.

If your problem persists, try to disable both addons (Weak Auras and HandyNotes: Dragonflight).

Tell us the results of the 3 steps to know if is a problem of 1 addon only or is a problem with the 2 addons at the same time.

Regards

**Comment by Dairyman** [comment]
More likely a problem with [LibUIDropDownMenu](https://legacy.curseforge.com/wow/addons/libuidropdownmenu/files/5054647), latest version of it fixed a version conflict and reference `NewFeature` which is in the error message.
