### ISSUE TITLE
Recursive Tooltip When Rare Icon is Underneath Blizzard Icon

### ISSUE THREAD

**Issue by ZachNewbery** [zarillion/handynotes-plugins#406]
**ADDON VERSION**: HandyNotes: Dragonflight v46

**Describe the bug**
It seems that there is a rather rare and obscure bug occurring when a Blizzard Rare Icon is on top of the rare icon provided by HandyNotes in which the tooltip will repeatedly populate with the rare drops - filling up the tooltip which expands until the screen is full. As far as I am aware, this error is due to HandyNotes, and doesn't seem to occur in any case other than that described -- unless the tooltip is not populated by HandyNotes.

I have been unable to work out what other conditions cause this error, as it does not happen every-time that the icon is overlaid. I imagine there may be something about the cursor being seen as entering and leaving the icon constantly as it quickly toggles between the Blizzard tooltip and HandyNotes?

**Screenshots**
![WoWScrnShot_020724_122515](https://github.com/zarillion/handynotes-plugins/assets/47321182/bec54ce3-7a49-4b7f-b08a-fbceb0346ae1)
![WoWScrnShot_020724_133537](https://github.com/zarillion/handynotes-plugins/assets/47321182/05eafad8-96c6-41b8-a8e5-470152597040)

**Comment by Krovikan** [comment]
Hello @ZachNewbery.

You tried disabling HandyNotes: Dragonflight and reloading the UI?

If disabling HandyNotes: Dragonflight all is the same, you can try to disable also HandyNotes (the base addon) ? (both disabled at the time).

Regards

**Comment by ZachNewbery** [comment]
Hi @Krovikan,

Yes I have tried all of those and it does fix the problem, which only occurs when both are enabled. However, after further testing the issue will only pop up if the HandyNotes: Dragonflight plugin is enabled alongside the tooltips from [RareScanner](https://www.curseforge.com/wow/addons/rarescanner). I imagine that both addons may use similar code to create tooltips, and cause multiple entry events on the rare icon to be sent as they do not recognise the presence of the other addon's tooltip.

However, as this is more an interactions between two addons causing the issue rather than this plugins interactions with the Blizzard UI, I don't believe it is an issue to fix anymore!

**Comment by Krovikan** [comment]
In this case, I'll close the issue. Is possible to reopen later if was necessary.

Regards
