### ISSUE TITLE
Feature / Support please the AV / dailys: Fringe Benefits

### ISSUE THREAD

**Issue by Fleymour** [zarillion/handynotes-plugins#410]
hey would be nice to have a marker on the map where the daily quest NPC is and my / our current progress in the Achievement. if possible also which daily is today up :)

(https://www.wowhead.com/achievement=19507/fringe-benefits)

**Comment by Dathwada** [comment]
This achievement was added in commit 16cbdd5. This will be included in the next release.

> if possible also which daily is today up

This was not implemented.
