### ISSUE TITLE
ACM "Whelp, There It Is" suddenly missing in Valdrakken

### ISSUE THREAD

**Issue by Flanell88** [zarillion/handynotes-plugins#414]
**ADDON VERSION**: HandyNotes_Dragonflight-v62

**Describe the bug**
In the latest versions v60-62 the achievement for "Whelp, There It Is" in Valdrakken is missing on the map. V46 still had it in. There is no way to pick it in the zone list because Valdrakken is entirely mising since you changed it to "Actual Season" with hundreds of zones instead of only Dragonflight zones.

**Screenshots**
Cant put in screenshots.

**Comment by Dathwada** [comment]
The achievement "Whelp, There It Is" was move to Achievements.

You should be able to enable it in the Worlmapbutton menu -> Achievements -> Whelp, There It Is
![menu)](https://github.com/zarillion/handynotes-plugins/assets/57680823/dc07b518-91f3-414d-a822-219b06f2ee02)

**Comment by Dathwada** [comment]
I will close this issue now. If you still can't find the achievement as described above, please feel free to contact us again.
