### ISSUE TITLE
Skinning Profession Item - TWW Azj-Kahet (City of Threads)

### ISSUE THREAD

**Issue by tfmonk** [zarillion/handynotes-plugins#415]
[Nerubian's Slicking Iron](https://www.wowhead.com/beta/item=226346/nerubians-slicking-iron)
Map ID: 2216
Quest ID: 83920
Item ID: 226346
Coords: 44.59 49.25

**Comment by Ioney** [comment]
Thank you for your help. If you find more, please feel free to share them with us.
