### ISSUE TITLE
Suggestion: Hide Rep from Rare/treasures after 1st time of war band looting it

### ISSUE THREAD

**Issue by tfmonk** [zarillion/handynotes-plugins#418]
it appears for some rares (possible treasures as well?) trigger a second quest on their first kill, i suspect this is for the rep for the war band tracking so you can only get it on the first kill.

Is it possible to track these additional quest ids and remove the rep gain from the tool tip to make it a bit more accurate after the initial kill so people know they wont get additional rep?

**Comment by m4tjz** [comment]
I have been investigating this for a while with another user on TWW Beta, we finally figured out that there is a new API function called C_QuestLog.IsQuestFlaggedCompletedOnAccount(questID) that returns true for those quest if you already killed the rare and it will not drop the reputation for you again. This seems to reset on the weekly reset.

**Comment by joshuadbeil** [comment]
Unfortunately your suspicion is wrong. Warband first-time rewards do not get tracked by an extra quest id. It's the same quests and they also don't have an additional `warband` flag. The second quest you mention will also be completed by each consecutive character that kills the rare that week and a hidden background check will see if it was already completed by your Warband. Theoretically there's a function `C_QuestLog.IsQuestFlaggedCompletedOnAccount()` to see if a quest is flagged as completed on your account but it's unreliable with repeatable quests as it requires you to log onto the character(s) that previously completed the quest to set the flag from `true` to `false` after a daily or weekly reset

**Comment by tfmonk** [comment]
@joshuadbeil from my experience it seems to be functioning as expected for the tracking quests from the rares, but that's not to say there isn't any current or previous bugs with this new functionality that could of produced a different result.

For example if i did C_QuestLog.IsQuestFlaggedCompletedOnAccount() for a rare tracking quest that i did before the reset on a different character it returned true on beta after the reset it's returning false, and i haven't logged onto the character that killed it after the daily reset.
