### ISSUE TITLE
PrePatch: A number of issues

### ISSUE THREAD

**Issue by Tovrin** [zarillion/handynotes-plugins#419]
As reported by BugCatcher (same bug reported ... one for each zone)

2x ...Ons/HandyNotes_Dragonflight/zones/zaralek_cavern.lua:754: attempt to call local 'WarSupply' (a nil value)
[string "@HandyNotes_Dragonflight/zones/zaralek_cavern.lua"]:754: in main chunk

Locals:
ADDON_NAME = "HandyNotes_Dragonflight"
ns = <table> {
 GROUP_HIDDEN75 = <table> {
 }
 NameResolver = <table> {
 }
 DRAGON_CUSTOMIZATIONS = <table> {
 }
 color = <table> {
 }
 WorldMapDataProvider = <table> {
 }
 requirement = <table> {
 }
 status = <table> {
 }
 COLORS = <table> {
 }
 tomtom = <table> {
 }
 group_types = <table> {
 }
 maps = <table> {
 }
 DRUID_GLYPHS = <table> {
 }
 tooltip = <table> {
 }
 icons = <table> {
 }
 expansion = 10
 groups = <table> {
 }
 Map = <table> {
 }
 professions = <table> {
 }
 node = <table> {
 }
 reward = <table> {
 }
 optionDefaults = <table> {
 }
 options = <table> {
 }
 GROUP_HIDDEN = <table> {
 }
 Group = <table> {
 }
 locale = <table> {
 }
 MinimapDataProvider = HandyNotes_DragonflightMinimapDP {
 }
 Interval = <table> {
 }
 poi = <table> {
 }
 addon = <table> {
 }
 GROUP_ALPHA75 = <table> {
 }
}
L = <table> {
 trilvarus_loreweaver_note = "Collect a {object:Singing Fragment} to get {spell:382076} and use the {object:Uncharded Focus} to spawn the rare."
 spawns_at_night = "{note:Spawns only at night. (After 18:30 server time)}"
 fringe_benefits_note = "Complete 8 of the daily quests to earn the achievement."
 druid_glyphs_label = "Druid Glyphs"
 soa_03_fangli_hoot_note_e = "Combine the pieces to recieve {item:207827} and begin {quest:77237} for {npc:207697} in {location:Valdrakken}."
 pt_ench_forgotten_arcane_tome_note = "Lying on the floor to the right of the entrance to a tomb."
 magical_bloom_note = "Chase the {npc:210544} until he reveals the treasure."
 options_icons_decay_covered_chest = "Decay Covered Chest"
 dracthyr_supply_chest = "Dracthyr Supply Chest"
 river_camp_note = "{note:This rare only spawns when {faction:Clan Aylaag} Camp in {location:River Camp}.}"
 leather = "Leather"
 prismatic_leaper_school_label = "Prismatic Leaper School"
 new_perspective_note = "Take a picture with the S.E.L.F.I.E. camera at the vista. The location will be marked by a purple light circle as soon as you are in camera mode.

If you dont get credit towards the achievement, change your angle."
 soa_15_tyrhold_statue_note = "Approach the Tyrhold Statue with the {item:208092} and channel until the orb glows bright red."
 fruitface_note = "Offer {npc:209950} {dot:Pink} your help to get {spell:421446}, then {item:208837s} become visible on the ground. Pick them up to let {npc:209980} {dot:Yellow} appear. Attack and follow him until he jumps in the water {dot:Red} and summons {npc:209966} and {npc:209913}."
 options_icons_djaradin_cache_desc = "Display possible locations of {object:Djaradin Cache}."
 plate = "Plate"
 loyal_magmammoth_sabellian_quatermaster_note = "Purchase {item:201839} |cFFFFD700(800 gold)|r from either {npc:199036} or {npc:188623}."
 enkine_note = "Kill {npc:193137}, {npc:193138} or {npc:193139} along the lava river to get {item:201092}, use it and fish near {npc:191866} in the lava."
 temperamental_skyclaw_note_end = "Ask about the saddled slyvern and present {npc:190892} the collected "dishes"."
 obsidian_citadel_rare_note = "You and other players have to return a total of %dx {item:191264} to %s. To craft a key you need to combine 30x {item:191251} and 3x {item:193201}, you can get these items from {location:Obsidian Citadel} mobs."
 soa_13_great_place_a_note = "On a stack of boxes inside the entrance to the {location:Auction House}."
 options_toggle_per_map_settings = "Use zone-specific settings"
 hard = "Hard"
 bag = "Bag"
 options_icons_ritual_offering_desc = "Display possible locations of {object:Ritual Offerings}."
 grand_flames_journal_note = "Click on the {object:Stone Tablet} outside behind the hut."
 rumble_both_bags = "Rumble Coin and Foil Bag"
 pm_smith_grekka_anvilsmash = "Sits in the grass next to the ruined tower."
 options_icons_nokhud_do_it_desc = "Display helpful information for completing {achievement:16583}."
 silent_mark_note = "Target the correct animal and channel the matching item until {spell:426910} appears. {note:You must attune with 10+ animals.}

Channel {item:210764} onto {npc:210892}.

Channel {item:210767} onto {npc:211347}, {npc:211283}, or

**Comment by Dathwada** [comment]
This will be fixed in the next release, which will be probably be released later today.

**Comment by hollo6** [comment]
Another one:

6x HandyNotes_Dragonflight/core/requirements.lua:178: attempt to call global 'GetFactionInfoByID' (a nil value)
[string "@HandyNotes_Dragonflight/core/requirements.lua"]:178: in function `GetText'
[string "@HandyNotes_Dragonflight/core/nodes.lua"]:227: in function `Prepare'
[string "@HandyNotes_Dragonflight/core/map.lua"]:165: in function `Prepare'
[string "@HandyNotes_Dragonflight/core/core.lua"]:239: in function <HandyNotes_Dragonflight/core/core.lua:228>
[string "=(tail call)"]: ?
[string "@HandyNotes/HandyNotes.lua"]:338: in function <HandyNotes/HandyNotes.lua:326>
[string "=[C]"]: ?
[string "@HandyNotes/HandyNotes.lua"]:56: in function <HandyNotes/HandyNotes.lua:51>
[string "@HandyNotes/HandyNotes.lua"]:322: in function `RefreshAllData'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:593: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:592>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:596: in function `OnMapChanged'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:295: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:294>
[string "=[C]"]: in function `OnMapChanged'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:60: in function `SetMapID'
[string "@Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:1045: in function `QuestMapFrame_ShowQuestDetails'
[string "@Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:1119: in function `QuestMapFrame_OpenToQuestDetails'
[string "@Blizzard_ObjectiveTracker/Blizzard_QuestObjectiveTracker.lua"]:65: in function `OnBlockHeaderClick'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerBlock.lua"]:258: in function `OnHeaderClick'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerBlock.lua"]:349: in function <..._ObjectiveTracker/Blizzard_ObjectiveTrackerBlock.lua:347>

GetFactionInfoByID has been moved to C_Reputation.GetFactionDataByID, need to replace this in common.lua, requirements.lua, util.lua, azure_span.lua, waking_shores.lua.

**Comment by Dathwada** [comment]
This should now be fixed with the release of v63. You can download it on [CurseForge](https://www.curseforge.com/wow/addons/handynotes-dragonflight/files/5561389) also please make sure to update [HandyNotes](https://www.curseforge.com/wow/addons/handynotes) to the newest version (>= v1.6.20.2).
