### ISSUE TITLE
Error on login "attempt to call global 'GetFactionInfoByID' (a nil value)"

### ISSUE THREAD

**Issue by Tequima** [zarillion/handynotes-plugins#422]
**ADDON VERSION**: v57

Error on log-in.

Message: Interface/AddOns/HandyNotes_Dragonflight/common.lua:930: attempt to call global 'GetFactionInfoByID' (a nil value)
Time: Wed Jul 24 18:32:17 2024
Count: 1
Stack: Interface/AddOns/HandyNotes_Dragonflight/common.lua:930: attempt to call global 'GetFactionInfoByID' (a nil value)
[string "@Interface/AddOns/HandyNotes_Dragonflight/common.lua"]:930: in main chunk

Locals: ADDON_NAME = "HandyNotes_Dragonflight"
ns = <table> {
 GROUP_HIDDEN75 = <table> {
 }
 NameResolver = <table> {
 }
 DRAGON_CUSTOMIZATIONS = <table> {
 }
 color = <table> {
 }
 WorldMapDataProvider = <table> {
 }
 requirement = <table> {
 }
 status = <table> {
 }
 COLORS = <table> {
 }
 tomtom = <table> {
 }
 group_types = <table> {
 }
 maps = <table> {
 }
 tooltip = <table> {
 }
 icons = <table> {
 }
 expansion = 10
 groups = <table> {
 }
 Map = <table> {
 }
 professions = <table> {
 }
 node = <table> {
 }
 reward = <table> {
 }
 optionDefaults = <table> {
 }
 options = <table> {
 }
 GROUP_HIDDEN = <table> {
 }
 Group = <table> {
 }
 locale = <table> {
 }
 MinimapDataProvider = HandyNotes_DragonflightMinimapDP {
 }
 Interval = <table> {
 }
 poi = <table> {
 }
 addon = <table> {
 }
 GROUP_ALPHA75 = <table> {
 }
}
L = <table> {
 trilvarus_loreweaver_note = "Collect a {object:Singing Fragment} to get {spell:382076} and use the {object:Uncharded Focus} to spawn the rare."
 spawns_at_night = "{note:Spawns only at night. (After 18:30 server time)}"
 druid_glyphs_label = "Druid Glyphs"
 soa_03_fangli_hoot_note_e = "Combine the pieces to recieve {item:207827} and begin {quest:77237} for {npc:207697} in {location:Valdrakken}."
 pt_ench_forgotten_arcane_tome_note = "Lying on the floor to the right of the entrance to a tomb."
 magical_bloom_note = "Chase the {npc:210544} until he reveals the treasure."
 options_icons_decay_covered_chest = "Decay Covered Chest"
 dracthyr_supply_chest = "Dracthyr Supply Chest"
 river_camp_note = "{note:This rare only spawns when {faction:Clan Aylaag} Camp in {location:River Camp}.}"
 leather = "Leather"
 new_perspective_note = "Take a picture with the S.E.L.F.I.E. camera at the vista. The location will be marked by a purple light circle as soon as you are in camera mode.

If you dont get credit towards the achievement, change your angle."
 soa_15_tyrhold_statue_note = "Approach the Tyrhold Statue with the {item:208092} and channel until the orb glows bright red."
 fruitface_note = "Offer {npc:209950} {dot:Pink} your help to get {spell:421446}, then {item:208837s} become visible on the ground. Pick them up to let {npc:209980} {dot:Yellow} appear. Attack and follow him until he jumps in the water {dot:Red} and summons {npc:209966} and {npc:209913}."
 options_icons_djaradin_cache_desc = "Display possible locations of {object:Djaradin Cache}."
 plate = "Plate"
 loyal_magmammoth_sabellian_quatermaster_note = "Purchase {item:201839} (800 gold) from either {npc:199036} or {npc:188623}."
 enkine_note = "Kill {npc:193137}, {npc:193138} or {npc:193139} along the lava river to get {item:201092}, use it and fish near {npc:191866} in the lava."
 temperamental_skyclaw_note_end = "Ask about the saddled slyvern and present {npc:190892} the collected "dishes"."
 obsidian_citadel_rare_note = "You and other players have to return a total of %dx {item:191264} to %s. To craft a key you need to combine 30x {item:191251} and 3x {item:193201}, you can get these items from {location:Obsidian Citadel} mobs."
 soa_13_great_place_a_note = "On a stack of boxes inside the entrance to the {location:Auction House}."
 options_toggle_per_map_settings = "Use zone-specific settings"
 hard = "Hard"
 bag = "Bag"
 options_icons_ritual_offering_desc = "Display possible locations of {object:Ritual Offerings}."
 grand_flames_journal_note = "Click on the {object:Stone Tablet} outside behind the hut."
 rumble_both_bags = "Rumble Coin and Foil Bag"
 pm_smith_grekka_anvilsmash = "Sits in the grass next to the ruined tower."
 options_icons_nokhud_do_it_desc = "Display helpful inform

**Comment by Dathwada** [comment]
Please update your addons.

[HandyNotes](https://www.curseforge.com/wow/addons/handynotes)
[HandyNotes: Dragonflight](https://www.curseforge.com/wow/addons/handynotes-dragonflight/files/all?page=1&pageSize=20)

**Comment by Tequima** [comment]
Thanks. The Wago version I downloaded via WoWUp must have been a bit behind.

Now fixed.

**Comment by Dathwada** [comment]
We are not uploading to wago.io.
