### ISSUE TITLE
Location of using https://www.wowhead.com/item=210840/empty-vial is wrong

### ISSUE THREAD

**Issue by Mini-Dragon** [zarillion/handynotes-plugins#429]
**ADDON VERSION**: (place version of the addon you have installed here)
Newest version

**Describe the bug**
The location of icon in Val'sharah is wrong. Should not in the dream grove, should in Thas'Talah.

X=45.03 Y=68.25

**Screenshots**

**Comment by Dathwada** [comment]
I guess Blizzard changed that. Because I'm pretty sure I used the Moonwell in Dreamgrove on my druid.

![](https://github.com/user-attachments/assets/f38a66ba-b948-4f1b-b6f2-0a952ce4f33b)
[Source](https://www.wowhead.com/item=210840/empty-vial#comments:id=5722897)
