### ISSUE TITLE
Turtle's Thanks Treasure (Isle of Dorn) doesn't look to accept Goldengill Trout any longer

### ISSUE THREAD

**Issue by Asterism314** [zarillion/handynotes-plugins#431]
**ADDON VERSION**: HN TWW v67

**Describe the bug**
Location: 40.88, 73.82

The tooltip from the map indicates that the turtle will accept Goldengill Trout and give treasure. However, there seems to be no way to give the turtle the Goldengill Trout.

**Screenshots**
https://i.imgur.com/elVH5ea.png
https://i.imgur.com/iIvqE4I.png

**Comment by tfmonk** [comment]
You need to leave the area and come back between the first step and the second step

**Comment by Asterism314** [comment]
> You need to leave the area and come back between the first step and the second step

This doesn't seem to change it. I went to The Ringing Deeps and then came back with no change, then tried going to Orgrimmar and coming back with no change. Do I need to go somewhere specific?

**Comment by tfmonk** [comment]
that did it for me on beta, I still have to do now so will try it in a bit

**Comment by tfmonk** [comment]
Did you give it all 5 Dornish Pike?

**Comment by Dathwada** [comment]
I did this today and it worked on the live servers as described.
1. Handed in 5x Dornish Pike
2. Leaved the area
3. Handed in 1x Goldengill Trout
4. ...

**Comment by Asterism314** [comment]
Apologies - I did not realize you need both the Dornish Pike AND the Goldengill Trout.
