### ISSUE TITLE
Feature Request: Right-click add to a rare scanner addon?

### ISSUE THREAD

**Issue by Protuhj** [zarillion/handynotes-plugins#434]
I use NPC Scan (yes I know it's old, but it still functions) and it'd be nice if I could right click a rare's icon and a menu item could conditionally be visible to add to NPC Scan automatically.

If that's not possible, maybe having a way to easily view the NPC's ID so I can add it manually.

**Comment by tfmonk** [comment]
We would recommend you switch to a rare scanner addon which is regularly updated, that way the npcs will be added, and with an addon which hasn't been updated in 4 years something can easily change that will break the functionality and with the varity of different rare scanners we wouldn't be able to support them them all as and they could easily change something in an update that would break handynotes.

**Comment by Protuhj** [comment]
I don't want every rare added, that's why I don't get a new rare scanner that's updated every week.

Also, the second part of this request was more general:

> If that's not possible, maybe having a way to easily view the NPC's ID so I can add it manually.
