### ISSUE TITLE
Sky-Captain's Sunken Cache clue missing flight path of three captains

### ISSUE THREAD

**Issue by Asterism314** [zarillion/handynotes-plugins#436]
**ADDON VERSION**: v73

**Describe the bug**
Clicking on the Treasure Chest "Sky-Captain's Sunken Cache", would previously display the flight path of the other three captains. Currently, it only displays one of them.

**Screenshots**

https://i.imgur.com/quO91i3.png

**Comment by Dathwada** [comment]
I have changed that. The routes of the captains you have already spoken to are now hidden.

**Comment by Asterism314** [comment]
Oh, I see! Apologies for the noise then.
