### ISSUE TITLE
suggestion / feature: filter rares by rep collected

### ISSUE THREAD

**Issue by Fleymour** [zarillion/handynotes-plugins#441]
as title says. would be nice to filter rares or change color of skull icon if Rep isnt collected.
also its currently debated if rep is a weekly thing from rares - so if that true this feature would be even bigger

**Comment by tfmonk** [comment]
Its classed as a reward so the rares should be blue if you have a reward to claim from it, such as rep, items, mounts and when you have everything it will go white.

The rep was weekly on beta so we are assuming it follow the same logic

**Comment by MysticalOS** [comment]
I came here to request same thing. It's important to kill each one per week for rep in early weeks and it'd be nice if the icon was just a diff color or something for uncollected rep, regardless of whether or not all other loot/objectives complete.

I think way it is now is purple if uncollected white if all collected. maybe red if rep not collected?

**Comment by zarillion** [comment]
This should already be possible. A couple releases ago reps were changed to reward-line items. If you uncheck the other reward types and enable just rep, the blue-state of the skulls should depend only on the rep (assuming you have the adventurer achievement already for that zone, we're looking at achievement options later).

You could then take it one step further and check "Hide rares if all rewards known" and it would only show rares you still need rep from.

**Comment by MysticalOS** [comment]
Yeah I realize could do it that way, but some of us also want to track those too, just want to track them separately in some kind of visible way

**Comment by rwygand** [comment]
I'd also like an indicator on the map regarding rep. Something like

Blue - you have not collected all the rewards
Purple - You've collected rep this week, but have other rewards you could collect
White - You've collected everything from this rare

I think Tomcat's Tours puts an aura glow on rares you've killed this week, and even that would be great. Just something so that at a glance of the map I can understand how many more rares I need in that zone.

**Comment by zarillion** [comment]
Alright you rascals, ask and you shall receive. Go download v92.

**Comment by rwygand** [comment]
Thanks, I was working on a PR but I don't know this code base (or wow addon dev really) at all!

**Comment by MysticalOS** [comment]
I had also tried to look at code to see if I could hack it in other night but had trouble finding where right things were called and gave up. :D

**Comment by zarillion** [comment]
Oh no. The author of DBM saying your code is hard to read is one way to feel self concious.

![the-s-impsons-bush](https://github.com/user-attachments/assets/242a0cf9-b79c-41b0-b9bf-08b410c8e305)

**Comment by MysticalOS** [comment]
Ha, it's not bad code but obviously when you have utility functions here and there I don't know structure I'm having to path trace things back and then getting lost. :)
