### ISSUE TITLE
Typo: Inscription knowledge item wrong quest ID

### ISSUE THREAD

**Issue by nbartley** [zarillion/handynotes-plugins#446]
**ADDON VERSION**: Latest

Line 433 in ringing_deeps.lua

map.nodes[48563432] = PT.Inscription({quest = 83883, id = 226310}) -- Runic Scroll

Should be

map.nodes[48563432] = PT.Inscription({quest = 83884, id = 226310}) -- Runic Scroll

**Comment by tfmonk** [comment]
Thanks for the information @nbartley this will be fixed in the next release
