### ISSUE TITLE
[Dragonflight] Line Break Issues

### ISSUE THREAD

**Issue by n-jones0** [zarillion/handynotes-plugins#448]
**ADDON VERSION**: 77

**Describe the bug**
Some POIs have the info added to the tooltip shifted down a line from where it should be. Known examples below.

**Screenshots**
#### Siege on Dragonbane Keep
This one is easy to fix, you can just move this line *below* the loop, right before it is shown
```
                if ns:GetOpt('show_loot') then
                    for i, reward in ipairs(SIEGE_ON_DRAGONBANE_KEEP_REWARDS) do
                        if reward:IsEnabled() then
                            reward:Render(GameTooltip)
                        end
                    end
                    GameTooltip:AddLine(' ')
                end
                GameTooltip:Show()
```
![image](https://github.com/user-attachments/assets/bb23b329-6831-4697-8e59-88ad410a9e63)

#### Grand Hunt (continent, not zone)
This one is a little harder to fix, because doing the previous fix makes the *zone* tooltip go too high
![image](https://github.com/user-attachments/assets/1ca578b7-d8c6-43ae-ad6f-69014f6ec29d)

**Comment by ghost** [comment]
this will be fixed in the next release
