### ISSUE TITLE
Misinformation in tooltip

### ISSUE THREAD

**Issue by GoaGifflar** [zarillion/handynotes-plugins#457]
**ADDON VERSION**: 11.0.2

**Describe the bug**
Sturdy chest #3 tooltip is wrong in Delve: The Skittering Breach, chest is located outside the building while map tooltip states outside. 

**Screenshots**
![Wow_SjFRCcEHk5](https://github.com/user-attachments/assets/9690ac9e-021d-4485-8b6b-a87aed959d30)
![Wow_HNImO0YLur](https://github.com/user-attachments/assets/e280716e-3cf0-4528-a588-1d9786fac805)

**Comment by tfmonk** [comment]
thanks @GoaGifflar this will be fixed in v96
