### ISSUE TITLE
[Bestial Underground Cleaver] showing up for non eligible classes

### ISSUE THREAD

**Issue by muiqo** [zarillion/handynotes-plugins#459]
**ADDON VERSION**: v100
**Describe the bug**
The item [[Bestial Underground Cleaver]](https://www.wowhead.com/item=221251/bestial-underground-cleaver) does show up on the tooltip of rares on my priest despite wowhead stating that it only drops for paladins/warriors/death knights.

**Screenshots**

![grafik](https://github.com/user-attachments/assets/519bbfd7-6a60-4612-827e-20ea227f8b0d)

**Comment by adavak** [comment]
nope, can be loot any class.

**Comment by Dathwada** [comment]
I can confirm this, it drop for me while playing on my balance druid.

**Comment by muiqo** [comment]
Thanks for confirming, guess Wowhead is wrong and i'm just unlucky 🫠
