### ISSUE TITLE
can no longer make own pins on maps. 

### ISSUE THREAD

**Issue by Booggg** [zarillion/handynotes-plugins#462]
Can no longer use keybinds to make a custom icon on the map. Was working last week, but no longer.

**Comment by Dairyman** [comment]
That is a feature of [HandyNotes](https://legacy.curseforge.com/wow/addons/handynotes) itself.

**Comment by Dathwada** [comment]
I close this as this is not a feature from us.
The only thing I can think of is that you may have installed a new addon that overrides this keybinding, because there was no new version for Hadynotes.
