### ISSUE TITLE
[Bug] Handynotes Shadowlands Treasures bug in the Maw

### ISSUE THREAD

**Issue by Kryptaria** [zarillion/handynotes-plugins#466]
**ADDON VERSION**: v83 (updated 11/1/24)

**Describe the bug**
In the Maw at the Kyrian assault. Mousing over the minimap gives this error:

3x .../HandyNotes_ShadowlandsTreasures/handler/handler.lua:897: bad argument #1 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@HandyNotes_ShadowlandsTreasures/handler/handler.lua"]:897: in function <.../HandyNotes_ShadowlandsTreasures/handler/handler.lua:893>
[string "@HandyNotes_ShadowlandsTreasures/handler/handler.lua"]:951: in function <.../HandyNotes_ShadowlandsTreasures/handler/handler.lua:914>
[string "@HandyNotes_ShadowlandsTreasures/handler/handler.lua"]:1002: in function <.../HandyNotes_ShadowlandsTreasures/handler/handler.lua:967>
[string "=(tail call)"]: ?
[string "@HandyNotes_ShadowlandsTreasures/handler/handler.lua"]:1207: in function <.../HandyNotes_ShadowlandsTreasures/handler/handler.lua:1180>
[string "=[C]"]: ?
[string "@HandyNotes/HandyNotes.lua"]:56: in function <HandyNotes/HandyNotes.lua:51>
[string "@HandyNotes/HandyNotes.lua"]:166: in function <HandyNotes/HandyNotes.lua:165>

Locals:
(*temporary) = "%s (%s)"
(*temporary) = nil
(*temporary) = "|cff19ff19Taralynd|r"
(*temporary) = "string expected, got nil"

**Comment by Dathwada** [comment]
Hello, is not our addon. There are two HandyNotes: Shadowlands versions, please report this to the other version or use our version.
