### ISSUE TITLE
Incorrect locale id

### ISSUE THREAD

**Issue by pzhukov** [zarillion/handynotes-plugins#471]
https://github.com/zarillion/handynotes-plugins/blob/0bfbc4882322d0cbbef2a02cb583c9c12787f2f3/plugins/11_TheWarWithin/localization/ruRU.lua#L2

@Hubbotu, shall it be `ruRU`?

**Comment by Krovikan** [comment]
> https://github.com/zarillion/handynotes-plugins/blob/0bfbc4882322d0cbbef2a02cb583c9c12787f2f3/plugins/11_TheWarWithin/localization/ruRU.lua#L2
> 
> @Hubbotu, shall it be `ruRU`?

Thanks for your heads up. Will be solved with next release.

Regards
