### ISSUE TITLE
Anima Shards Bugged 49/50

### ISSUE THREAD

**Issue by Kovacht** [zarillion/handynotes-plugins#56]
Hey! My achievement count says that I have 49/50 anima shards but my handy notes indicates that I collected them all. I don't know where it started to bug but I really don't want check the 50 anima shards again to see which one I left off or bugged. 
![WoWScrnShot_120120_004838](https://user-images.githubusercontent.com/75297531/100706676-04cf1a00-336f-11eb-8bf7-a8ca477b195e.jpg)

**Comment by zarillion** [comment]
This is likely an issue with the achievement itself and not the addon. If the crystal is not shown, your character truly does have that quest id flipped `true` right now. I would double-check you got the three crystals in Spires of Ascension, since those are not displayed on the Bastion map.

**Comment by Kovacht** [comment]
You were right, it's the last one of Spires of Ascension,

Thank you for your time, sorry about the mistake!

**Comment by zarillion** [comment]
All good, glad you found it!
