### ISSUE TITLE
Unticking Rares in settings panel unticks for all zones

### ISSUE THREAD

**Issue by fearkite** [zarillion/handynotes-plugins#57]
It seems that if you untick to show rares in one continent, for example for Revendreth, it unticks it for all other locations. I just want the plugin to work for The Maw and nothing else.

Thanks team!

**Comment by zarillion** [comment]
Look for the "Use zone-specific settings" option in the upcoming `v25` release.

![image](https://user-images.githubusercontent.com/64381982/100981153-0255f700-350c-11eb-8292-00b16a260c19.png)
