### ISSUE TITLE
SL: Wrong spawn for Akros

### ISSUE THREAD

**Issue by skupfer** [zarillion/handynotes-plugins#61]
Akros spawns at 34.0 74.8. The given location is wrong!

![image](https://user-images.githubusercontent.com/4295187/101265960-513d9f80-374b-11eb-8e7c-120f317c69c3.png)

**Comment by zarillion** [comment]
Akros was moved to the correct location in [`6dbd3dc`](https://github.com/zarillion/handynotes-plugins/commit/6dbd3dca24d8c9716b3c476cbfab1a052e5c3d80#diff-ce1b9d7e558d4d772bd12bc375d3626e64216e0b1b3d8c9b429642ca48212a2fR284), which was released as part of `v25` yesterday.

**Comment by skupfer** [comment]
I have v25 installed. The location for him was shown at his old location. So not fixed I guess?

**Comment by zarillion** [comment]
Your screenshot shows skulls from multiple addons. If you are referring to that purplish skull underneath your cursor in the screenshot above, that is not my addon. What other addon are you running that puts skull icons on the map in the Maw?

**Comment by skupfer** [comment]
I am referring to the green dot from TomTom. He wasn't shown there. 

EDIT: at the time of the screenshot I already killed him. I will try to log onto a twink. Need a few

**Comment by zarillion** [comment]
He's definitely there. Make sure you haven't hidden the node accidentally by restoring all hidden nodes from the right-click context menu of any other node. If you have already killed him today, his red dot will be gone unless you have "Show completed" checked in the quick-toggle menu.

**Comment by skupfer** [comment]
Ok. On my twink the location is correctly shown. I know my screenshot is after-kill but the red dot wasn't there (checked the location due to a wowhead comment)! Maybe I have to wipe saved vars for my main.
