### ISSUE TITLE
All rares are shown, no option to turn off transmog? I only care for pets/mounts/toys

### ISSUE THREAD

**Issue by strickland** [zarillion/handynotes-plugins#62]
Since the merge of all bfa together and the plugin has been not that useful for me, all rares are showing to me and I dont care for them.

Previously I had only toys/pets/mounts tick option and these are the only things I want to track, i.e. I want the blue skull to show only for these, but now its showing for everything, I dont care for weapons, or transmog, how do I disable these?

**Comment by zarillion** [comment]
There will be some options in one of the upcoming releases to filter different types of rewards from the tooltips.

**Comment by zarillion** [comment]
The upcoming release has an option to turn off transmog rewards.
