### ISSUE TITLE
Incorect Completed shards count.

### ISSUE THREAD

**Issue by stefanvmihai** [zarillion/handynotes-plugins#67]
I think the addon tracks on the entire account and not by character. This makes it hard to collect all 50 on one toon if you already picked up some random ones with another.

As you can see in the linked picture I am showing 43/50 shards but can only see 4 more on the current character.

http://prntscr.com/w1qcw0

This is prob due to the fact I prob already picked up 3 while doing random stuff with my other character.

**Comment by Dathwada** [comment]
I think your last three shards are still in the Spires of Ascension dungeon.
Could you please check this ?

And if you want to track things only for your current character you could use the option "Use character achievements".

**Comment by stefanvmihai** [comment]
Yes, indeed they are there. Thank you for the quick reply. I will close this false bug :).

**Comment by stefanvmihai** [comment]
False bug. The missing 3 shards were in Spires of Ascension.
