### ISSUE TITLE
HandyNotes Shadowlands - high cpu usage

### ISSUE THREAD

**Issue by Daeveren** [zarillion/handynotes-plugins#69]
First of all thank you for your addon, it's absolutely excellent (and same for the BfA one).
I've decided to open an issue here instead of posting in the comments section on Curse, maybe this is worth investigating further.

This is after it running for 2 mins.
![image](https://user-images.githubusercontent.com/6321337/102250187-e7bc4e80-3f0b-11eb-8eec-26b954fbde5b.png)

I can't figure out which part or function of the addon is causing the big cpu usage.
It might be a bug, or this might just be the way it works, but thought I'd post it here.

**Comment by ascott18** [comment]
Discussion on this issue ended up all in https://github.com/zarillion/handynotes-plugins/issues/75 - see my latest comment there for info on how to determine what is causing this.
