### ISSUE TITLE
handy notes sorrowban

### ISSUE THREAD

**Issue by obarr1138** [zarillion/handynotes-plugins#70]
i just did this achievment but found an extra thing to add to your tips which works great if you purchase the scroll of teleportation to theather of pain it puts you right next to the sword. if you have already added that or know about that already just disreguard this but it does cut down traveltime and distance

**Comment by obarr1138** [comment]
btw it's one-eyed joby that sells the scroll

**Comment by zarillion** [comment]
The tooltip is updated for the next version, thanks!
