### ISSUE TITLE
HandyNotes_Shadownlands has been blocked 

### ISSUE THREAD

**Issue by taima7700** [zarillion/handynotes-plugins#71]
HandyNotes_Shadowlands has been blocked from an action only available to the Blizzard UI.
popup appears when trying to use a quest item from the quest log list.
Can Disable addon and it works fine, if I press Ignore I just get the same error after attempting to use item again.

**Comment by taima7700** [comment]
Note that using the item directly from the bag doesn't make this issue.

**Comment by zarillion** [comment]
I've seen this a few times but haven't digged in further. The Blizzard reporting for which addon is at fault is often wrong due to the way UI taint spreads around. Going to close this for now until I have more information.
