### ISSUE TITLE
Kyrian Tamed Larion paths

### ISSUE THREAD

**Issue by chrisdcarpenter** [zarillion/handynotes-plugins#72]
3 "flight" paths have been added to Elysian Hold for Kyrian players. These flight paths do not use the normal flight path system and instead fly players between two Tamed Larions, one in Elysian Hold and the other at certain places in Bastion. Could these paths be added?

**NPC Locations:**
Everdawn Commons - 67.49, 23.51 <-> 67.90, 27.34
Seat of Eternal Hymns - 64.55, 20.44 <-> 58.73, 28.96
Fate's Precipice - 22.36, 29.12 <-> 58.99, 11.62

NPC Location format 
Destination - Elysian Hold WP <-> Dest WP

**Comment by zarillion** [comment]
I'm going to pass on this feature. Especially with flying out now these are less useful.
