### ISSUE TITLE
remember teleporter lines in the maw

### ISSUE THREAD

**Issue by rml9ty** [zarillion/handynotes-plugins#74]
ahoy there! would it be possible to have the state of the teleporter connections (the line drawn between them) to be persistent? every time I change character I have to activate the teleporter paths again by clicking on them on the map. would be dope if there was a setting for saving them.

**Comment by zarillion** [comment]
Right now that are meant to be inspected on hover only. I may add a feature in the future to remember the state of all focused nodes in the plugin (not just the maw, but all zones), but for now I'm going to leave it as it is. Definitely not a bad feature idea but not something I want to tackle at this time.
