### ISSUE TITLE
Forest Edge mushroom missing

### ISSUE THREAD

**Issue by BradCOnGitHub** [zarillion/handynotes-plugins#77]
There's no icon showing for the Forest Edge mushroom in the Night Fae Ring
![image](https://user-images.githubusercontent.com/15109073/103449643-a4364400-4c70-11eb-949e-7c95073f2fa5.png)

**Comment by zarillion** [comment]
This plugin does not display those mushroom icons in the sanctum. You'll need to figure out which other plugin is adding those and report it there.
