### ISSUE TITLE
Wrong Ardenweald Rare Mob Name - Dustbrawl > Gormbore

### ISSUE THREAD

**Issue by coldwinter18** [zarillion/handynotes-plugins#81]
Greetings,

At Ardenweald, Gormhive area, there are 2 rares. The Left one is the Dustbrawl and the Right one is the Gormbore. For the Right one, you have the right name of it as a title but on the 2nd row in which you write the achievement name you say " Adventurer of Ardenweald - Dustbrawl". You should change that to Adventurer of Ardenweald - Gormbore.

Also, I don't know if you want to add this but the community has figured it out that in order to summon Gormbore, you should stand on the dusty/ earthquake thing on the ground and kill mobs there (neutral or hostile). You can check the Wowhead comments for Gormbore.

Thank you and congratulations on the amazing work.

**Comment by zarillion** [comment]
This is a Blizzard issue, not an issue with this addon:

![image](https://user-images.githubusercontent.com/64381982/107160324-28a87080-695b-11eb-845a-9ee8f9d51e24.png)

You'll notice in the actual achievement, Dustbrawl is listed twice, as is Soultwister Cero. Those duplicate criteria are actually for Gormbore and Faeflayer, but Blizzard never fixed it even though I reported it multiple times during beta.

I have added the spawn criteria for Gormbore in the upcoming release.
