### ISSUE TITLE
Rares dropping mounts (Ascended Council)

### ISSUE THREAD

**Issue by Arkios64** [zarillion/handynotes-plugins#85]
Rares that only drop a mount, but not 100%, don't seem to stay on the map, and there doesn't seem to be any option to make them stay either. It seems like any rare that has been killed for the achievement disappears, no matter if there is still loot you might want to get from it.

**Comment by Arkios64** [comment]
Apparently they reappeared, so it might just be, that it is automatically hiding them for the daily credit... which would be a nice feature, if it said anywhere that it does that, or maybe gave the option to disable it.
So, basically, not a real issue, but something that could be improved.

**Comment by zarillion** [comment]
You can tell the addon to display completed (killed) nodes using the "Show completed" option:

![image](https://user-images.githubusercontent.com/64381982/107157366-5e445e00-6949-11eb-8086-9c8afa8e4f07.png)
