### ISSUE TITLE
The note for Callous Concoctions is hidden by the daily quest in the small map view.

### ISSUE THREAD

**Issue by aa-chrismcfadyen** [zarillion/handynotes-plugins#88]
This note has a lot of useful information on it, but it's impossible to mouse over it unless you do the daily quest for it or make the map full screen.  It's completely hidden by the daily quest exclamation mark, which can't be hidden by any map options.

Could it be moved slightly (probably a bit to the left) so that it can be moused over.

**Comment by zarillion** [comment]
Fixed for the next release.
