### ISSUE TITLE
Chest map tooltips missing info.

### ISSUE THREAD

**Issue by dle0105** [zarillion/handynotes-plugins#89]
Not sure when this started, but when you open your map and hover over one of the chest icons that the game provides, there is no longer any info on possible drops from them.

**Comment by Krovikan** [comment]
Started with 9.0.5. Sorry for no other answer.

**Comment by Dairyman** [comment]
Fast check shows that `SetText`is not any more called, which was the current hook. It calls now `AddLine` ...

**Comment by Krovikan** [comment]
Yes, I read in other side that the API have changes.

ASAP, @zarillion will make the proper changes.

**Comment by zarillion** [comment]
The tooltip rewards should show up most of the time now. It still doesn't seem to work sometimes and when it does it renders the rewards outside the tooltip box. If a better solution doesn't arise I'll probably just rip the entire feature out until Blizzard adds a better method to hook into for Vignette tooltips (which is probably never).

Pull requests welcome 😃

**Comment by Dairyman** [comment]
Wouldn't calling Show with a sentinel help with that e.g:
```Lua
local ownCall = false
function(self)
    if ownCall then return end

    if addThings then
        -- add new content

        ownCall = true
        self:Show()
        ownCall = false
    end
end
```

**Comment by Wevah** [comment]
> Wouldn't calling Show with a sentinel help with that e.g:
> 
> ```lua
> local ownCall = false
> function(self)
>     if ownCall then return end
> 
>     if addThings then
>         -- add new content
> 
>         ownCall = true
>         self:Show()
>         ownCall = false
>     end
> end
> ```

I can confirm that this works.

@Dairyman, if you don't feel like whipping up a PR then I will.

**Comment by Dairyman** [comment]
@Wevah sure go ahead
