### ISSUE TITLE
wrong mirror tooptip

### ISSUE THREAD

**Issue by gaveer** [zarillion/handynotes-plugins#91]
hey there , the sinfall mirror tooptip is wrong 
![image](https://user-images.githubusercontent.com/45834601/111060561-d228d780-84ae-11eb-9a35-231f9964a768.png)

**Comment by zarillion** [comment]
Based on the picture, I'm not sure what the issue is here. That portal icon is not displayed by my addon. I only add portal icons to the maps inside Sinfall (upper and lower floors).

**Comment by gaveer** [comment]
@zarillion 
this is the map  with portals showing 
![Untitled](https://user-images.githubusercontent.com/45834601/111167440-31bbdb80-85b2-11eb-9ca4-492e762e5b22.jpg)

now when you mouse over the mouse on top of the **Sinfall** portal what do is it say 

its SAY : **Pridefall Hamlet** and Pridefall portal is not here

**Comment by gaveer** [comment]
Edit : never mind its from **blizzard side**
