### ISSUE TITLE
Chest tooltips not displaying correctly since fix

### ISSUE THREAD

**Issue by Petrol30** [zarillion/handynotes-plugins#92]
The tooltip's for chest mouseovers are not being displayed correctly.
It's missing the black backdrop.

https://i.imgur.com/RucHnly.png

**Comment by Krovikan** [comment]
I have also as the screenshot shows.

In https://github.com/zarillion/handynotes-plugins/issues/89#issuecomment-799141504 you will see the explanation of the Author. Is in Blizzard's side.

**Comment by Wevah** [comment]
The fix in https://github.com/zarillion/handynotes-plugins/issues/89#issuecomment-799398409 appears to work to fix this.
