### ISSUE TITLE
Beasts of Bastion completion wrong

### ISSUE THREAD

**Issue by BradCOnGitHub** [zarillion/handynotes-plugins#97]
![image](https://user-images.githubusercontent.com/15109073/112707095-ac201180-8e76-11eb-96a4-f6013a9fd1ff.png)

![image](https://user-images.githubusercontent.com/15109073/112707099-b2ae8900-8e76-11eb-9224-90c417d7c94a.png)

**Comment by Dathwada** [comment]
It's not wrong, the green names under the achievement name shows that you had already killed the rars for this achievement and the undefeated shows that you haven't killed the rars today.
