### ISSUE TITLE
Tazavesh NPCs/portals

### ISSUE THREAD

**Issue by linaori** [zarillion/handynotes-plugins#98]
As I've been unable to make something myself as I can't find any API documentation for the main HandyNotes plugin, would it be interesting to add these in this particular addon? The markings note the following: NPCs for the part where you have to get items to specific NPCs for the code word, and the exit of portals from the hub.

This is taken from my global handy notes SavedVariables and contains 2 zones:
 - 1989 (The Veiled Market)
 - 1993 (The Upper City)

I've added 1993 because it's a separate zone map in the boss room. There's 1 oddity because it seems the NPC required to open this portal is not available. This is the only unavailable portal I could find in the map that was locked in the portal room.
![image](https://user-images.githubusercontent.com/1754678/118482818-8cd68f80-b715-11eb-9bce-653b7f083e68.png)
![image](https://user-images.githubusercontent.com/1754678/118482668-5567e300-b715-11eb-8221-25440fc0ec1a.png)
![image](https://user-images.githubusercontent.com/1754678/118482690-5dc01e00-b715-11eb-914c-8a3dd75ec169.png)

If it's fairly simple to add, with a few pointers of which "classes" to use, I can probably also make a PR myself. The icons are improvised and could probably use more specific icons for the type of merchant to make finding them easier.

```lua
	["global"] = {
		[1989] = {
			[51873321] = {
				["cont"] = false,
				["icon"] = 19,
				["title"] = "Precious Gemstones",
				["desc"] = "",
			},
			[46373573] = {
				["cont"] = false,
				["icon"] = 19,
				["title"] = "Alchemist",
				["desc"] = "",
			},
			[45793047] = {
				["cont"] = false,
				["icon"] = 19,
				["title"] = "Rare Texts",
				["desc"] = "",
			},
			[42834404] = {
				["cont"] = false,
				["icon"] = 28,
				["title"] = "The P.O.S.T.",
				["desc"] = "",
			},
			[50063346] = {
				["title"] = "Tazamal (?)",
				["cont"] = false,
				["icon"] = 28,
				["desc"] = "No NPC to activate",
			},
			[51502743] = {
				["cont"] = false,
				["icon"] = 19,
				["title"] = "Magical Weapons",
				["desc"] = "",
			},
			[44782805] = {
				["cont"] = false,
				["icon"] = 19,
				["title"] = "Expert Tailor",
				["desc"] = "",
			},
			[48853884] = {
				["cont"] = false,
				["icon"] = 19,
				["title"] = "Fine Cuisine",
				["desc"] = "",
			},
			[39883348] = {
				["cont"] = false,
				["icon"] = 28,
				["title"] = "Myza's Oasis",
				["desc"] = "",
			},
			[19805100] = {
				["cont"] = false,
				["icon"] = 28,
				["title"] = "Tazamal Port",
				["desc"] = "",
			},
			[50076133] = {
				["cont"] = false,
				["icon"] = 28,
				["title"] = "Multifarious Menagerie",
				["desc"] = "",
			},
			[44713328] = {
				["cont"] = false,
				["icon"] = 19,
				["title"] = "Exotic Spices",
				["desc"] = "",
			},
			[45273919] = {
				["cont"] = false,
				["icon"] = 19,
				["title"] = "Fossil Collector",
				["desc"] = "",
			},
			[42523679] = {
				["cont"] = false,
				["icon"] = 19,
				["title"] = "Thrift Instruments",
				["desc"] = "",
			},
			[36443271] = {
				["cont"] = false,
				["icon"] = 19,
				["title"] = "Overpriced Art",
				["desc"] = "",
			},
		},
		[1993] = {
			[77474412] = {
				["cont"] = false,
				["icon"] = 28,
				["title"] = "Tazamal Port",
				["desc"] = "",
			},
		},
	},
```

**Comment by zarillion** [comment]
I'll look into getting this info added. Unfortunately any icons added to the map in a dungeon will only appear on the world map and not the minimap due to Blizzard restricting access to player positioning inside dungeons and raids.

**Comment by zarillion** [comment]
Closing this as Shadowlands is over. This was generally solved by WAs telling you where to go based on what you were carrying.
